import { Module } from '../types';

export const module3: Module = {
    id: "3",
    title: { es: "3. Generación de Imágenes y Home Staging con IA", pt: "3. Geração de Imagens e Home Staging com IA" },
    description: { es: "Crea imágenes impactantes para tus anuncios, realiza home staging virtual para vaciar y decorar propiedades, y genera visualizaciones arquitectónicas con IA.", pt: "Crie imagens impactantes para os seus anúncios, realize home staging virtual para esvaziar e decorar imóveis, e gere visualizações arquitetónicas com IA." },
    icon: "image-generation",
    hero: {
      title: { es: "Visualiza el Potencial de cada Propiedad con IA", pt: "Visualize o Potencial de cada Imóvel com IA" },
      subtitle: { es: "Transforma espacios vacíos en hogares deseables, mejora tus fotos y crea imágenes que venden sin necesidad de fotógrafos o decoradores caros.", pt: "Transforme espaços vazios em lares desejáveis, melhore as suas fotos e crie imagens que vendem sem necessidade de fotógrafos ou decoradores caros." },
      image: "https://picsum.photos/1200/600?random=3",
    },
    content: {
      learnTitle: { es: "Qué aprenderás a crear y mejorar", pt: "O que vai aprender a criar e melhorar" },
      points: [
        { es: "Técnicas de 'home staging' virtual para amueblar espacios vacíos y eliminar objetos indeseados.", pt: "Técnicas de 'home staging' virtual para mobilar espaços vazios e eliminar objetos indesejados." },
        { es: "Mejorar la iluminación, el color y la composición de tus fotos de propiedades existentes.", pt: "Melhorar a iluminação, a cor e a composição das suas fotos de imóveis existentes." },
        { es: "Generar diferentes estilos de decoración (minimalista, nórdico, industrial) para una misma habitación.", pt: "Gerar diferentes estilos de decoração (minimalista, nórdico, industrial) para um mesmo cómodoo." },
        { es: "Crear imágenes fotorrealistas de exteriores, fachadas y jardines con diferentes acabados.", pt: "Criar imagens fotorrealistas de exteriores, fachadas e jardins com diferentes acabamentos." },
        { es: "Diseñar imágenes conceptuales y de marketing para redes sociales y campañas publicitarias.", pt: "Desenhar imagens conceptuais e de marketing para redes sociais e campanhas publicitárias." },
        { es: "Escribir prompts efectivos para obtener resultados fotorrealistas en herramientas de IA.", pt: "Escrever prompts eficazes para obter resultados fotorrealistas em ferramentas de IA." },
      ],
    },
    resources: {
      title: { es: "Recursos de Diseño con IA", pt: "Recursos de Design com IA" },
      downloads: [
          { 
          text: { es: "Guía de Prompts para Home Staging con IA", pt: "Guia de Prompts para Home Staging com IA" },
          url: "/docs/guia_prompts_homestaging.pdf" 
        },
        { 
          text: { es: "Checklist: Fotografía para Edición con IA", pt: "Checklist: Fotografia para Edição com IA" },
          url: "/docs/checklist_fotografia_ia.pdf" 
        },
        { 
          text: { es: "Guía Rápida: Estilos de Decoración para IA", pt: "Guia Rápido: Estilos de Decoração para IA" },
          url: "/docs/guia_estilos_decoracion_ia.pdf" 
        }
      ],
    },
    video: {
      title: { es: "Demostración Práctica: El Poder del Diseño de Interiores con IA", pt: "Demonstração Prática: O Poder do Design de Interiores com IA" },
      embedUrl: "https://www.youtube.com/embed/5j5U55yN_7s",
    },
    flashcards: [
      {
        question: { es: "¿Qué es el 'home staging'?", pt: "O que é 'home staging'?" },
        answer: { es: "Es una técnica de marketing inmobiliario que consiste en preparar una vivienda para su venta o alquiler, mejorando su aspecto para hacerla más atractiva para el mayor número de compradores potenciales.", pt: "É uma técnica de marketing imobiliário que consiste em preparar uma habitação para venda ou aluguer, melhorando o seu aspeto para a tornar mais atrativa para o maior número de potenciais compradores." },
        explanation: { es: "El objetivo del home staging es despersonalizar la vivienda, optimizar el espacio, la luz y la decoración para que los visitantes puedan imaginarse viviendo en ella. Esto acelera la venta y a menudo permite obtener un precio más alto. No se trata de ocultar defectos, sino de resaltar el potencial del inmueble.", pt: "O objetivo do home staging é despersonalizar a habitação, otimizar o espaço, a luz e a decoração para que os visitantes se possam imaginar a viver nela. Isto acelera a venda e muitas vezes permite obter um preço mais alto. Não se trata de esconder defeitos, mas de realçar o potencial do imóvel." }
      },
      {
        question: { es: "¿Qué es el 'home staging virtual'?", pt: "O que é 'home staging virtual'?" },
        answer: { es: "Es la versión digital del home staging. Utiliza software (a menudo con IA) para añadir o quitar muebles y decorar una foto de una habitación, en lugar de hacerlo físicamente.", pt: "É a versão digital do home staging. Utiliza software (frequentemente com IA) para adicionar ou remover móveis e decorar uma foto de um cómodo, em vez de o fazer fisicamente." },
        explanation: { es: "El home staging virtual es mucho más rápido y económico que el tradicional. Permite mostrar el potencial de una vivienda vacía, amueblándola digitalmente con un estilo moderno y neutro. También se puede usar para 'vaciar' digitalmente una habitación con muebles anticuados o muy personales, ayudando a los compradores a ver el espacio en sí mismo.", pt: "O home staging virtual é muito mais rápido e económico do que o tradicional. Permite mostrar o potencial de uma habitação vazia, mobilando-a digitalmente com um estilo moderno e neutro. Também pode ser usado para 'esvaziar' digitalmente um cómodo com móveis antiquados ou muito pessoais, ajudando os compradores a ver o espaço em si." }
      },
      {
        question: { es: "¿Qué es la 'IA Generativa' en el contexto de las imágenes?", pt: "O que é a 'IA Generativa' no contexto das imagens?" },
        answer: { es: "Es un tipo de inteligencia artificial que puede crear contenido nuevo y original, como imágenes, a partir de una descripción en texto (prompt).", pt: "É um tipo de inteligência artificial que pode criar conteúdo novo e original, como imagens, a partir de uma descrição em texto (prompt)." },
        explanation: { es: "Los modelos de IA Generativa, como DALL-E, Midjourney o Imagen, han sido entrenados con miles de millones de imágenes y sus descripciones. Cuando le das un prompt, la IA no busca una imagen existente, sino que 'entiende' los conceptos y crea una imagen completamente nueva desde cero que coincide con tu descripción. Esta es la tecnología base del home staging virtual y la creación de imágenes con IA.", pt: "Os modelos de IA Generativa, como DALL-E, Midjourney ou Imagen, foram treinados com milhares de milhões de imagens e as suas descrições. Quando lhe dá um prompt, a IA não procura uma imagem existente, mas 'entende' os conceitos e cria uma imagem completamente nova do zero que corresponde à sua descrição. Esta é a tecnologia base do home staging virtual e da criação de imagens com IA." }
      },
      {
        question: { es: "¿Qué es un 'prompt' para la generación de imágenes?", pt: "O que é um 'prompt' para a geração de imagens?" },
        answer: { es: "Es la instrucción de texto que le das a la IA para que genere una imagen. La calidad y el detalle del prompt determinan la calidad y precisión del resultado.", pt: "É a instrução de texto que dá à IA para que ela gere uma imagem. A qualidade e o detalhe do prompt determinam a qualidade e a precisão do resultado." },
        explanation: { es: "Un buen prompt es descriptivo y específico. En lugar de 'un salón', un buen prompt sería: 'Un salón luminoso y moderno, fotorrealista, con un sofá gris, suelo de madera y una gran ventana con vistas a un jardín'. Incluir detalles sobre el estilo, la iluminación y la composición es clave.", pt: "Um bom prompt é descritivo e específico. Em vez de 'uma sala', um bom prompt seria: 'Uma sala de estar luminosa e moderna, fotorrealista, com um sofá cinzento, chão de madeira e uma grande janela com vista para um jardim'. Incluir detalhes sobre o estilo, a iluminação e a composição é fundamental." }
      },
      {
        question: { es: "¿Qué es 'inpainting' o 'relleno generativo'?", pt: "O que é 'inpainting' ou 'preenchimento generativo'?" },
        answer: { es: "Es una técnica de IA donde seleccionas una parte de una imagen y le pides a la IA que la elimine y rellene el hueco de forma coherente con el resto de la imagen.", pt: "É uma técnica de IA onde seleciona uma parte de uma imagem e pede à IA que a elimine e preencha o espaço de forma coerente com o resto da imagem." },
        explanation: { es: "Esta es la técnica usada para 'vaciar' una habitación. Seleccionas un sofá viejo en una foto y le das a la IA el prompt 'eliminar este objeto'. La IA analiza el entorno (la pared de detrás, el suelo de debajo) y genera la parte de la pared y el suelo que estaban ocultos por el sofá. Es extremadamente útil para limpiar y despersonalizar fotos de propiedades.", pt: "Esta é a técnica usada para 'esvaziar' um cómodo. Seleciona um sofá velho numa foto e dá à IA o prompt 'eliminar este objeto'. A IA analisa o ambiente (a parede por trás, o chão por baixo) e gera a parte da parede e do chão que estavam ocultas pelo sofá. É extremamente útil para limpar e despersonalizar fotos de propriedades." }
      },
      {
        question: { es: "¿Qué es 'outpainting' o 'expansión generativa'?", pt: "O que é 'outpainting' ou 'expansão generativa'?" },
        answer: { es: "Es una técnica de IA que expande una imagen más allá de sus bordes originales, imaginando y creando lo que podría haber alrededor.", pt: "É uma técnica de IA que expande uma imagem para além das suas bordas originais, imaginando e criando o que poderia estar ao redor." },
        explanation: { es: "Si tienes una foto de una propiedad que está demasiado recortada, puedes usar el outpainting para 'añadir más cielo' por arriba o 'más jardín' por los lados. La IA analiza la imagen existente y genera una continuación coherente. Esto es muy útil para ajustar el encuadre de una foto y hacerla más atractiva visualmente.", pt: "Se tem uma foto de uma propriedade que está demasiado cortada, pode usar o outpainting para 'adicionar mais céu' por cima ou 'mais jardim' pelos lados. A IA analisa a imagem existente e gera uma continuação coerente. Isto é muito útil para ajustar o enquadramento de uma foto e torná-la mais atraente visualmente." }
      },
      {
        question: { es: "Menciona 3 palabras clave en un prompt para obtener imágenes fotorrealistas.", pt: "Mencione 3 palavras-chave num prompt para obter imagens fotorrealistas." },
        answer: { es: "'fotorrealista', 'ultra detallado', 'fotografía profesional', '8k'.", pt: "'fotorrealista', 'ultra detalhado', 'fotografia profissional', '8k'." },
        explanation: { es: "Los modelos de IA han sido entrenados con millones de fotos etiquetadas. Usar términos que describen la calidad de una foto real ayuda a la IA a entender que no quieres una ilustración o un dibujo. Frases como 'fotografía de arquitectura', 'lente de 35mm', 'iluminación cinematográfica' o 'hiperrealista' guían a la IA hacia un resultado que imita una fotografía de alta calidad.", pt: "Os modelos de IA foram treinados com milhões de fotos etiquetadas. Usar termos que descrevem a qualidade de uma foto real ajuda a IA a entender que não quer uma ilustração ou um desenho. Frases como 'fotografia de arquitetura', 'lente de 35mm', 'iluminação cinematográfica' ou 'hiper-realista' guiam a IA para um resultado que imita uma fotografia de alta qualidade." }
      },
      {
        question: { es: "¿Cómo se describe la iluminación en un prompt?", pt: "Como se descreve a iluminação num prompt?" },
        answer: { es: "Usando términos descriptivos como 'luz natural brillante', 'luz suave de la mañana', 'iluminación cálida y acogedora' o 'luz dramática del atardecer (hora dorada)'.", pt: "Usando termos descritivos como 'luz natural brilhante', 'luz suave da manhã', 'iluminação quente e acolhedora' ou 'luz dramática do pôr do sol (hora dourada)'." },
        explanation: { es: "La iluminación es uno de los factores más importantes para el ambiente de una imagen. Ser específico es clave. 'Luz natural entrando por una gran ventana' produce un resultado muy diferente a 'luz ambiental suave de lámparas de diseño'. La IA entiende estos conceptos y los aplica para crear la atmósfera deseada.", pt: "A iluminação é um dos fatores mais importantes para o ambiente de uma imagem. Ser específico é fundamental. 'Luz natural a entrar por uma grande janela' produz um resultado muito diferente de 'luz ambiente suave de candeeiros de design'. A IA entende estes conceitos e aplica-os para criar a atmosfera desejada." }
      },
      {
        question: { es: "¿Qué es 'upscaling'?", pt: "O que é 'upscaling'?" },
        answer: { es: "Es el proceso de aumentar la resolución (el tamaño y detalle) de una imagen usando IA, sin que pierda calidad o se vea pixelada.", pt: "É o processo de aumentar a resolução (o tamanho e o detalhe) de uma imagem usando IA, sem que perca qualidade ou fique pixelizada." },
        explanation: { es: "Las imágenes generadas por IA a veces se crean a una resolución media. Si necesitas imprimirla en un folleto o usarla en un banner grande, necesitas más resolución. El 'upscaling' con IA no solo estira la imagen, sino que 'inventa' los píxeles intermedios de forma inteligente, manteniendo las líneas nítidas y los detalles claros. Es como convertir una foto de baja calidad en una de alta calidad.", pt: "As imagens geradas por IA por vezes são criadas com uma resolução média. Se precisar de a imprimir num folheto ou usá-la num banner grande, precisa de mais resolução. O 'upscaling' com IA não se limita a esticar a imagem, mas 'inventa' os píxeis intermédios de forma inteligente, mantendo as linhas nítidas e os detalhes claros. É como transformar uma foto de baixa qualidade numa de alta qualidade." }
      },
      {
        question: { es: "¿Qué es 'style transfer'?", pt: "O que é 'style transfer'?" },
        answer: { es: "Es una técnica de IA que aplica el estilo visual de una imagen (ej. un cuadro de Van Gogh) a otra imagen (ej. una foto de una casa).", pt: "É uma técnica de IA que aplica o estilo visual de uma imagem (ex. um quadro de Van Gogh) a outra imagem (ex. uma foto de uma casa)." },
        explanation: { es: "Aunque en inmobiliaria se usa menos para estilos artísticos, el concepto es útil para cambiar estilos de decoración. Puedes tener una foto de un salón y darle a la IA una imagen de referencia de un salón de estilo industrial, pidiéndole que 'aplique el estilo de la segunda imagen a la primera'. La IA cambiará los muebles, texturas y colores para que coincidan con el estilo de referencia.", pt: "Embora no setor imobiliário seja menos usado para estilos artísticos, o conceito é útil para mudar estilos de decoração. Pode ter uma foto de uma sala e dar à IA uma imagem de referência de uma sala de estilo industrial, pedindo-lhe que 'aplique o estilo da segunda imagem à primeira'. A IA mudará os móveis, texturas e cores para que coincidam com o estilo de referência." }
      },
      {
        question: { es: "Diferencia entre 'fotorrealista' e 'hiperrealista'.", pt: "Diferença entre 'fotorrealista' e 'hiper-realista'." },
        answer: { es: "Ambos buscan un aspecto de foto real. 'Fotorrealista' es el estándar. 'Hiperrealista' o 'ultra detallado' le pide a la IA que se esfuerce aún más en los pequeños detalles, texturas e imperfecciones.", pt: "Ambos procuram um aspeto de foto real. 'Fotorrealista' é o padrão. 'Hiper-realista' ou 'ultra detalhado' pede à IA que se esforce ainda mais nos pequenos detalhes, texturas e imperfeições." },
        explanation: { es: "Para la mayoría de los casos, 'fotorrealista' es suficiente. Cuando quieres una imagen de muy alta gama, añadir 'hiperrealista' o 'ultra-detailed' puede hacer que la IA genere texturas más creíbles en la madera, reflejos más precisos en el cristal o pequeñas imperfecciones que hacen que la imagen parezca menos 'perfecta' y, por lo tanto, más real.", pt: "Para a maioria dos casos, 'fotorrealista' é suficiente. Quando quer uma imagem de altíssima gama, adicionar 'hiper-realista' ou 'ultra-detailed' pode fazer com que a IA gere texturas mais credíveis na madeira, reflexos mais precisos no vidro ou pequenas imperfeições que fazem com que a imagem pareça menos 'perfeita' e, portanto, mais real." }
      },
      {
        question: { es: "Ejemplo de prompt para cambiar el color de una fachada.", pt: "Exemplo de prompt para mudar a cor de uma fachada." },
        answer: { es: "Con la imagen de la fachada seleccionada: 'Cambia el color de las paredes exteriores a un blanco roto moderno, manteniendo las ventanas y el tejado como están. El resultado debe ser fotorrealista'.", pt: "Com a imagem da fachada selecionada: 'Mude a cor das paredes exteriores para um branco sujo moderno, mantendo as janelas e o telhado como estão. O resultado deve ser fotorrealista'." },
        explanation: { es: "Esta es una aplicación muy práctica del 'inpainting'. Le permite a un agente mostrar a un cliente cómo se vería una casa con una simple capa de pintura, ayudando a superar objeciones sobre una fachada con un color anticuado. Ser específico en el color ('blanco roto' en lugar de 'blanco') y en lo que NO debe cambiar ('manteniendo las ventanas...') es clave para un buen resultado.", pt: "Esta é uma aplicação muito prática do 'inpainting'. Permite a um agente mostrar a um cliente como uma casa ficaria com uma simples camada de tinta, ajudando a superar objeções sobre uma fachada com uma cor antiquada. Ser específico na cor ('branco sujo' em vez de 'branco') e no que NÃO deve mudar ('mantendo as janelas...') é fundamental para um bom resultado." }
      },
      {
        question: { es: "¿Qué es la 'relación de aspecto' (aspect ratio) en la generación de imágenes?", pt: "O que é a 'relação de aspeto' (aspect ratio) na geração de imagens?" },
        answer: { es: "Es la proporción entre el ancho y el alto de una imagen (ej. 16:9 para formato panorámico, 1:1 para cuadrado, 9:16 para vertical/stories).", pt: "É a proporção entre a largura e a altura de uma imagem (ex. 16:9 para formato panorâmico, 1:1 para quadrado, 9:16 para vertical/stories)." },
        explanation: { es: "Definir la relación de aspecto es importante para adaptar la imagen al canal donde se va a usar. Una imagen para la cabecera de una web debe ser panorámica (16:9), mientras que una para una publicación de Instagram puede ser cuadrada (1:1) y una para una Story debe ser vertical (9:16). La mayoría de las herramientas de IA permiten especificar esto con un parámetro en el prompt (ej. `--ar 16:9`).", pt: "Definir a relação de aspeto é importante para adaptar a imagem ao canal onde será usada. Uma imagem para o cabeçalho de um site deve ser panorâmica (16:9), enquanto uma para uma publicação do Instagram pode ser quadrada (1:1) e uma para uma Story deve ser vertical (9:16). A maioria das ferramentas de IA permite especificar isto com um parâmetro no prompt (ex. `--ar 16:9`)." }
      },
      {
        question: { es: "¿Cómo se pide a la IA que simule un tipo de lente de cámara?", pt: "Como se pede à IA que simule um tipo de lente de câmara?" },
        answer: { es: "Añadiendo términos fotográficos al prompt, como 'foto con gran angular' (para sensación de amplitud) o 'lente de 85mm con poca profundidad de campo' (para enfocar un detalle).", pt: "Adicionando termos fotográficos ao prompt, como 'foto com grande angular' (para sensação de amplitude) ou 'lente de 85mm com pouca profundidade de campo' (para focar um detalhe)." },
        explanation: { es: "La IA entiende el lenguaje de la fotografía. 'Gran angular' (wide-angle lens) es el término más útil en inmobiliaria, ya que es la lente que usan los fotógrafos profesionales para hacer que las habitaciones parezcan más grandes. Usar 'teleobjetivo' (telephoto lens) puede simular una foto tomada desde lejos, y 'macro' puede generar un detalle de una textura o material.", pt: "A IA entende a linguagem da fotografia. 'Grande angular' (wide-angle lens) é o termo mais útil no setor imobiliário, pois é a lente que os fotógrafos profissionais usam para fazer os quartos parecerem maiores. Usar 'teleobjetiva' (telephoto lens) pode simular uma foto tirada de longe, e 'macro' pode gerar um detalhe de uma textura ou material." }
      },
      {
        question: { es: "¿Qué es una 'imagen de referencia' en un prompt?", pt: "O que é uma 'imagem de referência' num prompt?" },
        answer: { es: "Es una imagen que subes junto con tu prompt de texto para que la IA la use como inspiración para el estilo, la composición o los colores de la nueva imagen.", pt: "É uma imagem que carrega juntamente com o seu prompt de texto para que a IA a use como inspiração para o estilo, a composição ou as cores da nova imagem." },
        explanation: { es: "Si te encanta el ambiente de una foto de una revista de decoración, puedes subir esa foto y escribir un prompt como: 'Crea un dormitorio principal usando el estilo y la paleta de colores de esta imagen de referencia'. La IA no copiará la imagen, sino que extraerá sus características estéticas y las aplicará a la nueva creación. Es una forma muy potente de guiar a la IA hacia un resultado específico.", pt: "Se adora o ambiente de uma foto de uma revista de decoração, pode carregar essa foto e escrever um prompt como: 'Cria um quarto principal usando o estilo e a paleta de cores desta imagem de referência'. A IA не copiará a imagem, mas extrairá as suas características estéticas e aplicá-las-á à nova criação. É uma forma muito potente de guiar a IA para um resultado específico." }
      },
      {
        question: { es: "Consideración ética clave al usar home staging virtual.", pt: "Consideração ética fundamental ao usar o home staging virtual." },
        answer: { es: "La transparencia. Se debe indicar claramente que la imagen ha sido decorada virtualmente para no engañar a los compradores potenciales.", pt: "A transparência. Deve-se indicar claramente que a imagem foi decorada virtualmente para não enganar os potenciais compradores." },
        explanation: { es: "El home staging virtual es para mostrar el potencial, no para falsear la realidad. Amueblar un espacio vacío es ético. Sin embargo, eliminar digitalmente un pilar estructural o cambiar la vista desde una ventana sería engañoso e ilegal. La buena práctica es añadir una pequeña marca de agua o texto en la descripción que diga 'Imagen decorada virtualmente' o 'Amueblamiento virtual'.", pt: "O home staging virtual serve para mostrar o potencial, não para falsear a realidade. Mobilar um espaço vazio é ético. No entanto, eliminar digitalmente um pilar estrutural ou mudar a vista de uma janela seria enganoso e ilegal. A boa prática é adicionar uma pequena marca de água ou texto na descrição que diga 'Imagem decorada virtualmente' ou 'Mobiliário virtual'." }
      },
      {
        question: { es: "¿Cómo se puede usar la IA para mejorar un jardín descuidado en una foto?", pt: "Como se pode usar a IA para melhorar um jardim descuidado numa foto?" },
        answer: { es: "Usando 'inpainting'. Se selecciona la zona del jardín y se le da un prompt como 'rellena esta área con césped verde y cuidado y algunos arbustos floridos'.", pt: "Usando 'inpainting'. Seleciona-se a zona do jardim e dá-se um prompt como 'preenche esta área com relva verde e cuidada e alguns arbustos floridos'." },
        explanation: { es: "El exterior de una casa es la primera impresión. Si el jardín está en mal estado, puede desanimar a los compradores. Con la IA, un agente puede seleccionar el área del césped seco y pedirle que lo reemplace por 'césped sano y frondoso'. Puede seleccionar una zona de tierra y pedirle que 'añada un macizo de flores coloridas'. Esto ayuda a mostrar el potencial del espacio exterior con muy poco esfuerzo.", pt: "O exterior de uma casa é a primeira impressão. Se o jardim estiver em mau estado, pode desanimar os compradores. Com a IA, um agente pode selecionar a área da relva seca e pedir-lhe que a substitua por 'relva saudável e exuberante'. Pode selecionar uma zona de terra e pedir-lhe que 'adicione um canteiro de flores coloridas'. Isto ajuda a mostrar o potencial do espaço exterior com muito pouco esforço." }
      },
      {
        question: { es: "¿Qué es un 'prompt negativo'?", pt: "O que é um 'prompt negativo'?" },
        answer: { es: "Es una parte del prompt donde le dices a la IA lo que NO quieres que aparezca en la imagen (ej. 'sin gente', 'sin texto', 'sin coches').", pt: "É uma parte do prompt onde diz à IA o que NÃO quer que apareça na imagem (ex. 'sem pessoas', 'sem texto', 'sem carros')." },
        explanation: { es: "A veces, la IA añade elementos no deseados. Los prompts negativos ayudan a limpiar el resultado. Por ejemplo, al generar una fachada, la IA podría añadir coches aparcados en la calle. Añadir `--no cars` (en Midjourney) o un parámetro de prompt negativo le indica a la IA que evite ese elemento. Es una herramienta muy útil para tener más control sobre la composición final.", pt: "Às vezes, a IA adiciona elementos indesejados. Os prompts negativos ajudam a limpar o resultado. Por exemplo, ao gerar uma fachada, a IA pode adicionar carros estacionados na rua. Adicionar `--no cars` (no Midjourney) ou um parâmetro de prompt negativo indica à IA para evitar esse elemento. É uma ferramenta muito útil para ter mais controlo sobre a composição final." }
      },
      {
        question: { es: "¿Cómo se puede crear una 'imagen de estilo de vida' con IA?", pt: "Como se pode criar uma 'imagem de estilo de vida' com IA?" },
        answer: { es: "Pidiendo a la IA que genere una escena que evoque una emoción o actividad, en lugar de solo describir un espacio. Ej: 'Una pareja joven riendo mientras cocinan en una cocina moderna y luminosa'.", pt: "Pedindo à IA que gere uma cena que evoque uma emoção ou atividade, em vez de apenas descrever um espaço. Ex: 'Um casal jovem a rir enquanto cozinham numa cozinha moderna e luminosa'." },
        explanation: { es: "Las imágenes de estilo de vida no venden la casa, venden el sueño. Son ideales para redes sociales o la sección 'Sobre Mí' de una web. Otros ejemplos: 'Una familia jugando en el jardín de un chalet en un día soleado, estilo fotografía publicitaria' o 'Una persona leyendo un libro en un balcón acogedor con vistas a la ciudad'. Estas imágenes conectan emocionalmente con el público objetivo.", pt: "As imagens de estilo de vida не vendem a casa, vendem o sonho. São ideais para redes sociais ou a secção 'Sobre Mim' de um site. Outros exemplos: 'Uma família a brincar no jardim de uma moradia num dia de sol, estilo fotografia publicitária' ou 'Uma pessoa a ler um livro numa varanda acolhedora com vista para a cidade'. Estas imagens conectam-se emocionalmente com o público-alvo." }
      },
      {
        question: { es: "¿Qué es un 'modelo de difusión' (diffusion model)?", pt: "O que é um 'modelo de difusão' (diffusion model)?" },
        answer: { es: "Es el tipo de tecnología de IA que está detrás de la mayoría de los generadores de imágenes modernos. Funciona añadiendo 'ruido' a una imagen y luego aprendiendo a quitarlo para crear una nueva.", pt: "É o tipo de tecnologia de IA que está por trás da maioria dos geradores de imagens modernos. Funciona adicionando 'ruído' a uma imagem e depois aprendendo a removê-lo para criar uma nova." },
        explanation: { es: "Imagina que tomas una foto y le añades gradualmente 'ruido' (píxeles aleatorios) hasta que es puro caos. El modelo de difusión aprende a hacer el proceso inverso: partiendo de un campo de ruido aleatorio y guiado por tu prompt, va 'limpiando' el ruido de forma iterativa hasta que emerge una imagen coherente. Es un proceso computacionalmente intensivo pero increíblemente potente para crear imágenes detalladas y originales.", pt: "Imagina que tira uma foto e lhe adiciona gradualmente 'ruído' (píxeis aleatórios) até ser puro caos. O modelo de difusão aprende a fazer o processo inverso: partindo de um campo de ruído aleatório e guiado pelo seu prompt, vai 'limpando' o ruído de forma iterativa até emergir uma imagem coerente. É um processo computacionalmente intensivo mas incrivelmente potente para criar imagens detalhadas e originais." }
      },
      {
        question: { es: "Menciona 2 estilos de decoración y las palabras clave para generarlos.", pt: "Mencione 2 estilos de decoração e as palavras-chave para os gerar." },
        answer: { es: "1. Industrial: 'ladrillo visto, tuberías de metal, hormigón'. 2. Nórdico: 'madera clara, paredes blancas, acogedor (hygge)'.", pt: "1. Industrial: 'tijolo à vista, tubos de metal, cimento'. 2. Nórdico: 'madeira clara, paredes brancas, acolhedor (hygge)'." },
        explanation: { es: "La IA asocia ciertas palabras con estilos visuales. Para el estilo Industrial, palabras como 'warehouse loft', 'exposed brick', 'metal beams' funcionan bien. Para el estilo Nórdico (o Escandinavo), palabras como 'scandinavian design', 'light wood', 'minimalist furniture', 'natural light' guían a la IA hacia ese estética limpia y cálida.", pt: "A IA associa certas palavras a estilos visuais. Para o estilo Industrial, palavras como 'warehouse loft', 'exposed brick', 'metal beams' funcionam bem. Para o estilo Nórdico (ou Escandinavo), palavras como 'scandinavian design', 'light wood', 'minimalist furniture', 'natural light' guiam a IA para essa estética limpa e acolhedora." }
      },
      {
        question: { es: "¿Qué es el 'renderizado arquitectónico' con IA?", pt: "O que é a 'renderização arquitetónica' com IA?" },
        answer: { es: "Es la creación de imágenes fotorrealistas de un edificio a partir de planos o bocetos, antes de que se construya. La IA está acelerando enormemente este proceso.", pt: "É a criação de imagens fotorrealistas de um edifício a partir de plantas ou esboços, antes de ser construído. A IA está a acelerar enormemente este processo." },
        explanation: { es: "Tradicionalmente, el renderizado 3D requería semanas de trabajo de un especialista. Ahora, un arquitecto puede subir un modelo 3D simple o incluso un boceto a una plataforma de IA, y con un prompt como 'renderiza este edificio con un acabado de hormigón y madera, en un entorno de bosque al atardecer', la IA puede generar un render de alta calidad en minutos. Esto es revolucionario para la promoción sobre plano.", pt: "Tradicionalmente, a renderização 3D exigia semanas de trabalho de um especialista. Agora, um arquiteto pode carregar um modelo 3D simples ou até um esboço para uma plataforma de IA, e com um prompt como 'renderiza este edifício com um acabamento em cimento e madeira, num ambiente de floresta ao pôr do sol', a IA pode gerar um render de alta qualidade em minutos. Isto é revolucionário para a promoção de imóveis em planta." }
      },
      {
        question: { es: "¿Puede la IA 'mejorar' una foto de móvil de baja calidad?", pt: "Pode a IA 'melhorar' uma foto de telemóvel de baixa qualidade?" },
        answer: { es: "Sí, las herramientas de IA pueden reducir el ruido, mejorar la nitidez, corregir la iluminación y aumentar la resolución (upscaling) para mejorar significativamente una foto de móvil.", pt: "Sim, as ferramentas de IA podem reduzir o ruído, melhorar a nitidez, corrigir a iluminação e aumentar a resolução (upscaling) para melhorar significativamente uma foto de telemóvel." },
        explanation: { es: "Muchas veces un agente necesita usar una foto rápida tomada con el móvil. Las herramientas de IA como Topaz Photo AI o las funciones de Adobe Photoshop AI pueden analizar la imagen y aplicar una serie de mejoras automáticas. Aunque no reemplaza a una buena foto original, puede convertir una foto mediocre en una imagen usable para marketing, lo cual es muy útil en situaciones de urgencia.", pt: "Muitas vezes um agente precisa de usar uma foto rápida tirada com o telemóvel. As ferramentas de IA como o Topaz Photo AI ou as funções do Adobe Photoshop AI podem analisar a imagem e aplicar uma série de melhorias automáticas. Embora não substitua uma boa foto original, pode transformar uma foto medíocre numa imagem utilizável para marketing, o que é muito útil em situações de urgência." }
      },
      {
        question: { es: "¿Qué es la 'consistencia de personaje/estilo' en IA?", pt: "O que é a 'consistência de personagem/estilo' em IA?" },
        answer: { es: "Es la capacidad de la IA para generar múltiples imágenes manteniendo el mismo estilo visual o las mismas características de un objeto o persona.", pt: "É a capacidade da IA para gerar múltiplas imagens mantendo o mesmo estilo visual ou as mesmas características de um objeto ou pessoa." },
        explanation: { es: "Esto es un desafío para la IA, pero está mejorando. Para un agente, es importante para generar diferentes vistas de una misma habitación decorada virtualmente. Se usan técnicas como fijar una 'semilla' (seed) o usar funciones de 'referencia de estilo' para indicarle a la IA que todas las imágenes de una serie deben tener la misma estética, los mismos muebles y la misma paleta de colores.", pt: "Isto é um desafio para a IA, mas está a melhorar. Para um agente, é importante para gerar diferentes vistas de um mesmo cómodo decorado virtualmente. Usam-se técnicas como fixar uma 'semente' (seed) ou usar funções de 'referência de estilo' para indicar à IA que todas as imagens de uma série devem ter a mesma estética, os mesmos móveis e a mesma paleta de cores." }
      },
      {
        question: { es: "¿Cómo se puede usar la IA para generar diferentes opciones de reforma?", pt: "Como se pode usar a IA para gerar diferentes opções de remodelação?" },
        answer: { es: "Tomando una foto de la habitación a reformar (ej. una cocina vieja) y pidiéndole a la IA que la rediseñe con diferentes estilos: 'rediseña esta cocina con un estilo moderno', 'ahora con un estilo rústico'.", pt: "Tirando uma foto do cómodo a remodelar (ex. uma cozinha velha) e pedindo à IA que a redesenhe com diferentes estilos: 'redesenha esta cozinha com um estilo moderno', 'agora com um estilo rústico'." },
        explanation: { es: "Esta es una herramienta de visualización muy potente para propiedades a reformar. Permite al comprador ver el potencial de la inversión. El agente puede presentar un 'antes' y varios 'después' generados por la IA, mostrando cómo podría quedar la cocina con una isla central, o cómo el salón podría abrirse al jardín. Esto ayuda al comprador a superar la barrera de una propiedad anticuada.", pt: "Esta é uma ferramenta de visualização muito potente para propriedades a remodelar. Permite ao comprador ver o potencial do investimento. O agente pode apresentar um 'antes' e vários 'depois' gerados pela IA, mostrando como a cozinha poderia ficar com uma ilha central, ou como a sala poderia abrir-se para o jardim. Isto ajuda o comprador a superar a barreira de uma propriedade antiquada." }
      },
      {
        question: { es: "Describe el proceso de 'textura virtual' con IA.", pt: "Descreva o processo de 'textura virtual' com IA." },
        answer: { es: "Es usar 'inpainting' para cambiar materiales. Se selecciona el suelo de una foto y se le pide a la IA: 'cambia este suelo por un parqué de madera de roble claro'.", pt: "É usar 'inpainting' para mudar materiais. Seleciona-se o chão de uma foto e pede-se à IA: 'muda este chão para um parquet de madeira de carvalho claro'." },
        explanation: { es: "Los materiales tienen un gran impacto en la percepción de una propiedad. Con la IA, se puede mostrar cómo se vería un salón con un suelo diferente, cómo quedaría una pared con un acabado de ladrillo visto, o cómo se vería la encimera de la cocina si fuera de mármol. Esto permite personalizar la visualización a los gustos del comprador sin necesidad de hacer ninguna obra.", pt: "Os materiais têm um grande impacto na perceção de uma propriedade. Com a IA, pode-se mostrar como uma sala ficaria com um chão diferente, como uma parede ficaria com um acabamento de tijolo à vista, ou como a bancada da cozinha ficaria se fosse de mármore. Isto permite personalizar a visualização aos gostos do comprador sem necessidade de fazer qualquer obra." }
      },
      {
        question: { es: "¿Qué es la 'edición basada en prompts'?", pt: "O que é a 'edição baseada em prompts'?" },
        answer: { es: "Es el futuro de la edición de imágenes. En lugar de usar herramientas manuales (pinceles, capas), simplemente le dices a la IA lo que quieres cambiar: 'haz el cielo más azul', 'ilumina esta esquina oscura'.", pt: "É o futuro da edição de imagens. Em vez de usar ferramentas manuais (pincéis, camadas), simplesmente diz à IA o que quer mudar: 'torna o céu mais azul', 'ilumina este canto escuro'." },
        explanation: { es: "Herramientas como Adobe Photoshop están integrando la IA de esta manera. Un agente puede seleccionar una zona de una foto que ha quedado demasiado oscura y escribir 'aumenta la exposición en esta área'. La IA realiza el ajuste de forma inteligente, entendiendo el contexto de la iluminación general. Esto democratiza la edición de fotos profesional, haciéndola accesible para no expertos.", pt: "Ferramentas como o Adobe Photoshop estão a integrar a IA desta forma. Um agente pode selecionar uma zona de uma foto que ficou demasiado escura e escrever 'aumenta a exposição nesta área'. A IA realiza o ajuste de forma inteligente, entendendo o contexto da iluminação geral. Isto democratiza a edição de fotos profissional, tornando-a acessível para não especialistas." }
      },
      {
        question: { es: "¿Cómo se puede visualizar una 'ampliación' de una casa con IA?", pt: "Como se pode visualizar uma 'ampliação' de uma casa com IA?" },
        answer: { es: "Usando 'outpainting' para expandir la foto de la casa y luego 'inpainting' para añadir la nueva estructura (ej. 'añade un porche acristalado en este lateral').", pt: "Usando 'outpainting' para expandir a foto da casa e depois 'inpainting' para adicionar a nova estrutura (ex. 'adiciona um alpendre envidraçado neste lado')." },
        explanation: { es: "Para propiedades con potencial de ampliación, mostrarlo es un gran argumento de venta. Un agente puede tomar la foto del jardín trasero, usar 'outpainting' para crear más espacio, y luego darle a la IA el prompt: 'Construye una piscina moderna en esta zona del jardín'. O para la casa misma, 'Añade un segundo piso a esta casa de una planta'. Estas visualizaciones ayudan a los compradores a entender y valorar el potencial de crecimiento de la propiedad.", pt: "Para propriedades com potencial de ampliação, mostrá-lo é um grande argumento de venda. Um agente pode tirar a foto do jardim traseiro, usar 'outpainting' para criar mais espaço, e depois dar à IA o prompt: 'Constrói uma piscina moderna nesta zona do jardim'. Ou para a própria casa, 'Adiciona um segundo andar a esta casa de um só piso'. Estas visualizações ajudam os compradores a entender e a valorizar o potencial de crescimento da propriedade." }
      },
      {
        question: { es: "¿Qué es una 'marca de agua digital' y por qué es importante?", pt: "O que é uma 'marca de água digital' e porque é importante?" },
        answer: { es: "Es un logo o texto semitransparente que se superpone en tus fotos para protegerlas contra el uso no autorizado y para reforzar tu marca.", pt: "É um logótipo ou texto semitransparente que se sobrepõe nas suas fotos para as proteger contra o uso não autorizado e para reforçar a sua marca." },
        explanation: { es: "Cuando publicas fotos de alta calidad, corres el riesgo de que otros las copien y las usen. Una marca de agua con tu logo o el nombre de tu web disuade de este robo. Además, cada vez que alguien comparte tu foto en redes sociales, tu marca viaja con ella. Las herramientas de IA también pueden aplicar marcas de agua automáticamente a todas las imágenes que generas o editas.", pt: "Quando publica fotos de alta qualidade, corre o risco de que outros as copiem e as usem. Uma marca de água com o seu logótipo ou o nome do seu site dissuade este roubo. Além disso, cada vez que alguém partilha a sua foto nas redes sociais, a sua marca viaja com ela. As ferramentas de IA também podem aplicar marcas de água automaticamente a todas as imagens que gera ou edita." }
      },
      {
        question: { es: "¿Cómo puede la IA ayudar a elegir la 'foto de portada' de un anuncio?", pt: "Como a IA pode ajudar a escolher a 'foto de capa' de um anúncio?" },
        answer: { es: "Analizando un conjunto de fotos de una propiedad y puntuándolas según su atractivo visual (composición, luz, color), prediciendo cuál tiene más probabilidades de generar clics.", pt: "Analisando um conjunto de fotos de uma propriedade e pontuando-as de acordo com o seu apelo visual (composição, luz, cor), prevendo qual tem maior probabilidade de gerar cliques." },
        explanation: { es: "La foto de portada es el elemento más importante de un anuncio online. Algunas herramientas de IA pueden analizar todas las fotos de una sesión y darles un 'score de atractivo'. Pueden detectar que una foto del salón con luz de tarde tiene mejor composición y colores más cálidos que la foto de la fachada. Al elegir la foto con la puntuación más alta como portada, se maximiza el Click-Through Rate (CTR) del anuncio.", pt: "A foto de capa é o elemento mais importante de um anúncio online. Algumas ferramentas de IA podem analisar todas as fotos de uma sessão e dar-lhes um 'score de atratividade'. Podem detetar que uma foto da sala com luz de tarde tem melhor composição e cores mais quentes do que a foto da fachada. Ao escolher a foto com a pontuação mais alta como capa, maximiza-se a Taxa de Cliques (CTR) do anúncio." }
      },
      {
        question: { es: "¿Puede la IA crear planos de planta 2D a partir de fotos?", pt: "Pode a IA criar plantas 2D a partir de fotos?" },
        answer: { es: "Sí, algunas aplicaciones de IA especializadas pueden analizar una serie de fotos o un vídeo de una propiedad y generar un plano de planta 2D aproximado con las distribuciones y medidas.", pt: "Sim, algumas aplicações de IA especializadas podem analisar uma série de fotos ou um vídeo de uma propriedade e gerar uma planta 2D aproximada com as distribuições e medidas." },
        explanation: { es: "Esta tecnología utiliza la visión por computador (Computer Vision) para interpretar la geometría de las habitaciones a partir de imágenes. Aunque puede no ser tan preciso como una medición manual, es una forma increíblemente rápida de generar un plano de planta visual para los anuncios. Esto ayuda a los compradores a entender la distribución del espacio mucho mejor que solo con fotos.", pt: "Esta tecnologia utiliza a visão computacional (Computer Vision) para interpretar a geometria dos cómodos a partir de imagens. Embora possa не ser tão precisa como uma medição manual, é uma forma incrivelmente rápida de gerar uma planta visual para os anúncios. Isto ajuda os compradores a entender a distribuição do espaço muito melhor do que apenas com fotos." }
      },
      {
        question: { es: "¿Qué es la 'iteración' en el proceso de generación de imágenes?", pt: "O que é a 'iteração' no processo de geração de imagens?" },
        answer: { es: "Es el proceso de refinar tu prompt y generar nuevas versiones de una imagen hasta que consigues el resultado deseado. Rara vez la primera imagen es la perfecta.", pt: "É o processo de refinar o seu prompt e gerar novas versões de uma imagem até conseguir o resultado desejado. Raramente a primeira imagem é a perfeita." },
        explanation: { es: "La generación de imágenes con IA es un diálogo. Generas una primera versión. La analizas: 'Me gusta el estilo, pero el sofá es demasiado grande'. Entonces, modificas el prompt: '...con un sofá gris de dos plazas...' y generas de nuevo. Este ciclo de generar, analizar y refinar es la forma de trabajar con estas herramientas para ir afinando el resultado hasta que se ajuste a tu visión.", pt: "A geração de imagens com IA é um diálogo. Gera uma primeira versão. Analisa-a: 'Gosto do estilo, mas o sofá é demasiado grande'. Então, modifica o prompt: '...com um sofá cinzento de dois lugares...' e gera novamente. Este ciclo de gerar, analisar e refinar é a forma de trabalhar com estas ferramentas para ir afinando o resultado até que se ajuste à sua visão." }
      },
      {
        question: { es: "Menciona una desventaja o riesgo de la IA generativa de imágenes.", pt: "Mencione uma desvantagem ou risco da IA generativa de imagens." },
        answer: { es: "Puede tener dificultades con detalles finos como las manos humanas, puede 'alucinar' y crear elementos extraños, y existe el riesgo de crear imágenes engañosas si no se usa éticamente.", pt: "Pode ter dificuldades com detalhes finos como as mãos humanas, pode 'alucinar' e criar elementos estranhos, e existe o risco de criar imagens enganosas se não for usada eticamente." },
        explanation: { es: "Aunque la tecnología es asombrosa, no es perfecta. A menudo genera personas con seis dedos o crea objetos que desafían la física. En el contexto inmobiliario, el mayor riesgo es el uso no ético, como eliminar digitalmente una torre de alta tensión que está al lado de la casa. La clave es usar la IA para mejorar la presentación, no para alterar la realidad fundamental de la propiedad.", pt: "Embora a tecnologia seja espantosa, não é perfeita. Frequentemente gera pessoas com seis dedos ou cria objetos que desafiam a física. No contexto imobiliário, o maior risco é o uso não ético, como eliminar digitalmente uma torre de alta tensão que está ao lado da casa. A chave é usar a IA para melhorar a apresentação, não para alterar a realidade fundamental da propriedade." }
      },
      {
        question: { es: "¿Cómo se puede simular un 'cambio de día a noche' en una foto de exterior?", pt: "Como se pode simular uma 'mudança de dia para noite' numa foto de exterior?" },
        answer: { es: "Usando una herramienta de edición con IA y un prompt como 'convierte esta foto de día en una foto nocturna, con las luces interiores de la casa encendidas y un cielo estrellado'.", pt: "Usando uma ferramenta de edição com IA e um prompt como 'converte esta foto de dia numa foto noturna, com as luzes interiores da casa acesas e um céu estrelado'." },
        explanation: { es: "Las fotos crepusculares (twilight photos) son muy atractivas y venden muy bien. Pero hacerlas requiere que un fotógrafo esté en la propiedad al atardecer. Con la IA, puedes tomar una foto a cualquier hora del día y transformarla. La IA entiende el concepto de 'noche', por lo que oscurecerá el entorno, encenderá las luces de las ventanas y cambiará el cielo, creando una imagen muy llamativa con un solo clic.", pt: "As fotos crepusculares (twilight photos) são muito atraentes e vendem muito bem. Mas fazê-las requer que um fotógrafo esteja na propriedade ao pôr do sol. Com a IA, pode tirar uma foto a qualquer hora do dia e transformá-la. A IA entende o conceito de 'noite', por isso escurecerá o ambiente, acenderá as luzes das janelas e mudará o céu, criando uma imagem muito chamativa com um único clique." }
      },
      {
        question: { es: "¿Por qué es importante el 'storytelling' visual en los anuncios?", pt: "Porque é importante o 'storytelling' visual nos anúncios?" },
        answer: { es: "Porque las personas conectan con historias, no con listas de características. Un conjunto de imágenes debe contar la historia de 'cómo sería vivir en esta casa'.", pt: "Porque as pessoas conectam-se com histórias, не com listas de características. Um conjunto de imagens deve contar a história de 'como seria viver nesta casa'." },
        explanation: { es: "La IA puede ayudar a crear este storytelling. En lugar de generar solo fotos de habitaciones, puedes generar una serie de imágenes: una foto del amanecer entrando por la ventana del dormitorio, una de una familia desayunando en la cocina, una de niños jugando en el jardín. Esta secuencia visual cuenta una historia y permite al comprador proyectarse emocionalmente en la propiedad, lo que es mucho más poderoso que simplemente listar '3 habitaciones, 2 baños'.", pt: "A IA pode ajudar a criar este storytelling. Em vez de gerar apenas fotos de quartos, pode gerar uma série de imagens: uma foto do amanhecer a entrar pela janela do quarto, uma de uma família a tomar o pequeno-almoço na cozinha, uma de crianças a brincar no jardim. Esta sequência visual conta uma história e permite ao comprador projetar-se emocionalmente na propriedade, o que é muito mais poderoso do que simplesmente listar '3 quartos, 2 casas de banho'." }
      },
      {
        question: { es: "¿Qué es el 'decluttering' digital?", pt: "O que é o 'decluttering' digital?" },
        answer: { es: "Es el proceso de usar IA para eliminar digitalmente el desorden y los objetos personales de una foto de una propiedad, haciendo que el espacio parezca más grande y neutro.", pt: "É o processo de usar IA para eliminar digitalmente a desordem e os objetos pessoais de uma foto de uma propriedade, fazendo com que o espaço pareça maior e mais neutro." },
        explanation: { es: "A menudo, las fotos de una casa habitada están llenas de objetos personales (fotos de familia, imanes en la nevera, juguetes). Esto distrae al comprador y le impide imaginarse su propia vida allí. El 'decluttering' digital usa la técnica de 'inpainting' para seleccionar y eliminar estos objetos, dejando un espacio limpio y despersonalizado que sirve como un lienzo en blanco para la imaginación del comprador.", pt: "Muitas vezes, as fotos de uma casa habitada estão cheias de objetos pessoais (fotos de família, ímanes no frigorífico, brinquedos). Isto distrai o comprador e impede-o de imaginar a sua própria vida ali. O 'decluttering' digital usa a técnica de 'inpainting' para selecionar e eliminar estes objetos, deixando um espaço limpo e despersonalizado que serve como uma tela em branco para a imaginação do comprador." }
      },
      {
        question: { es: "¿Puede la IA cambiar las estaciones en una foto de exterior?", pt: "Pode a IA mudar as estações numa foto de exterior?" },
        answer: { es: "Sí, puedes tomar una foto de una casa en invierno y pedirle a la IA: 'cambia esta escena a verano, con un césped verde, árboles con hojas y un cielo azul y soleado'.", pt: "Sim, pode tirar uma foto de uma casa no inverno e pedir à IA: 'muda esta cena para o verão, com relva verde, árvores com folhas e um céu azul e soalheiro'." },
        explanation: { es: "Vender una casa con jardín en invierno puede ser difícil, ya que las fotos muestran árboles sin hojas y un césped apagado. La IA puede transformar estas imágenes para mostrar el potencial de la propiedad en su mejor momento. Esto ayuda a los compradores a ver cómo será la casa en primavera o verano, haciendo el anuncio mucho más atractivo durante todo el año.", pt: "Vender uma casa com jardim no inverno pode ser difícil, pois as fotos mostram árvores sem folhas e uma relva sem vida. A IA pode transformar estas imagens para mostrar o potencial da propriedade no seu melhor momento. Isto ajuda os compradores a ver como a casa será na primavera ou no verão, tornando o anúncio muito mais atraente durante todo o ano." }
      },
      {
        question: { es: "¿Qué es una 'semilla' (seed) en la generación de imágenes?", pt: "O que é uma 'semente' (seed) na geração de imagens?" },
        answer: { es: "Es un número que sirve como punto de partida para la generación de una imagen. Usar la misma semilla con el mismo prompt producirá la misma imagen, lo que es útil para la consistencia.", pt: "É um número que serve como ponto de partida para a geração de uma imagem. Usar a mesma semente com o mesmo prompt produzirá a mesma imagem, o que é útil para a consistência." },
        explanation: { es: "La IA parte de 'ruido' aleatorio. La 'semilla' es el número que define ese punto de partida aleatorio. Si no especificas una semilla, la IA usa una diferente cada vez, por lo que obtienes imágenes distintas aunque el prompt sea idéntico. Si encuentras una imagen que te gusta y quieres hacer pequeñas variaciones, puedes copiar su número de semilla y usarlo en tus siguientes prompts. Esto te da más control y te permite mantener un estilo coherente.", pt: "A IA parte de 'ruído' aleatório. A 'semente' é o número que define esse ponto de partida aleatório. Se não especificar uma semente, a IA usa uma diferente de cada vez, pelo que obtém imagens distintas mesmo que o prompt seja idêntico. Se encontrar uma imagem de que gosta e quiser fazer pequenas variações, pode copiar o seu número de semente e usá-lo nos seus próximos prompts. Isto dá-lhe mais controlo e permite-lhe manter um estilo coerente." }
      },
      {
        question: { es: "¿Puede la IA ayudar a crear un logo para mi marca de agente?", pt: "Pode a IA ajudar a criar um logótipo para a minha marca de agente?" },
        answer: { es: "Sí, puedes pedirle a la IA que genere conceptos de logo. Ej: 'Crea un logo minimalista para un agente inmobiliario llamado Juan Pérez, usando las iniciales JP y la forma de una casa'.", pt: "Sim, pode pedir à IA que gere conceitos de logótipo. Ex: 'Cria um logótipo minimalista para um agente imobiliário chamado João Silva, usando as iniciais JS e a forma de uma casa'." },
        explanation: { es: "Aunque la IA todavía tiene problemas para generar texto perfecto dentro de las imágenes, es una herramienta fantástica para la ideación. Puede generar docenas de conceptos de logo en minutos. Un agente puede usar estas ideas como inspiración y luego llevar su concepto favorito a un diseñador gráfico para que lo pula y lo vectorice profesionalmente. Acelera enormemente la fase creativa del branding.", pt: "Embora a IA ainda tenha problemas para gerar texto perfeito dentro das imagens, é uma ferramenta fantástica para a ideação. Pode gerar dezenas de conceitos de logótipo em minutos. Um agente pode usar estas ideias como inspiração e depois levar o seu conceito favorito a um designer gráfico para que o refine e o vectorize profissionalmente. Acelera enormemente a fase criativa do branding." }
      },
      {
        question: { es: "¿Qué es 'ControlNet' en el contexto de la IA de imágenes?", pt: "O que é 'ControlNet' no contexto da IA de imagens?" },
        answer: { es: "Es una técnica avanzada que permite a la IA tener un control mucho más preciso sobre la composición de la imagen, usando un mapa de bordes, una pose o una segmentación como guía.", pt: "É uma técnica avançada que permite à IA ter um controlo muito mais preciso sobre a composição da imagem, usando um mapa de contornos, uma pose ou uma segmentação como guia." },
        explanation: { es: "Con los modelos de difusión normales, tienes un control limitado sobre la disposición exacta de los objetos. ControlNet resuelve esto. Puedes darle a la IA un boceto muy simple de una habitación (un cuadrado para un sofá, un círculo para una mesa) y la IA generará una imagen fotorrealista que respeta exactamente esa disposición. Es una herramienta muy potente para diseñadores y arquitectos que necesitan un control compositivo total.", pt: "Com os modelos de difusão normais, tem um controlo limitado sobre a disposição exata dos objetos. O ControlNet resolve isto. Pode dar à IA um esboço muito simples de um cómodo (um quadrado para um sofá, um círculo para uma mesa) e a IA gerará uma imagem fotorrealista que respeita exatamente essa disposição. É uma ferramenta muito potente para designers e arquitetos que precisam de um controlo composicional total." }
      }
    ]
};