import { Module } from '../types';

export const module2: Module = {
    id: "2",
    title: { es: "2. Valoración con IA", pt: "2. Avaliação com IA" },
    description: { es: "Utiliza modelos predictivos para realizar tasaciones precisas, analizar el mercado y asesorar a tus clientes con datos objetivos.", pt: "Utilize modelos preditivos para realizar avaliações precisas, analisar o mercado e aconselhar os seus clientes com dados objetivos." },
    icon: "valuation",
    hero: {
      title: { es: "Valoraciones Precisas con IA", pt: "Avaliações Precisas com IA" },
      subtitle: { es: "Domina las herramientas de Análisis Comparativo de Mercado (CMA) automatizadas para fijar precios competitivos.", pt: "Domine as ferramentas de Análise Comparativa de Mercado (CMA) automatizadas para definir preços competitivos." },
      image: "https://picsum.photos/1200/600?random=2",
    },
    content: {
      learnTitle: { es: "Qué aprenderás a dominar", pt: "O que vai aprender a dominar" },
      points: [
        { es: "Cómo funcionan los Modelos de Valoración Automatizada (AVM) y qué datos utilizan.", pt: "Como funcionam os Modelos de Avaliação Automatizada (AVM) e que dados utilizam." },
        { es: "A generar informes de Análisis Comparativo de Mercado (CMA) en minutos con IA.", pt: "A gerar relatórios de Análise Comparativa de Mercado (CMA) em minutos com IA." },
        { es: "A interpretar el 'score de confianza' de una valoración para entender su fiabilidad.", pt: "A interpretar o 'score de confiança' de uma avaliação para entender a sua fiabilidade." },
        { es: "Identificar las variables clave que más influyen en el valor de una propiedad.", pt: "Identificar as variáveis-chave que mais influenciam o valor de uma propriedade." },
        { es: "Analizar tendencias de mercado y proyecciones de precios para justificar tus valoraciones.", pt: "Analisar tendências de mercado e projeções de preços para justificar as suas avaliações." },
        { es: "Presentar datos de valoración de forma clara y persuasiva a tus clientes.", pt: "Apresentar dados de avaliação de forma clara e persuasiva aos seus clientes." },
      ],
    },
    resources: {
      title: { es: "Recursos y Plantillas de Valoración", pt: "Recursos e Modelos de Avaliação" },
      downloads: [
        { 
          text: { es: "Guía: Interpretando un Informe AVM", pt: "Guia: Interpretando um Relatório AVM" },
          url: "/docs/guia_interpretar_avm.pdf" 
        },
        { 
          text: { es: "Plantilla de Prompt para CMA con IA", pt: "Modelo de Prompt para CMA com IA" },
          url: "/docs/plantilla_prompt_cma.pdf" 
        },
        { 
          text: { es: "Checklist: Variables Clave en la Valoración", pt: "Checklist: Variáveis-Chave na Avaliação" },
          url: "/docs/checklist_variables_valoracion.pdf" 
        }
      ],
    },
    videos: [
      {
        title: { es: "Explicación: ¿Qué son los Modelos de Valoración Automatizada (AVM)?", pt: "Explicação: O que são os Modelos de Avaliação Automatizada (AVM)?" },
        embedUrl: "https://www.youtube.com/embed/i-c4a03i2AY",
      },
      {
        title: { es: "Video Tutorial Adicional 1", pt: "Vídeo Tutorial Adicional 1" },
        embedUrl: "https://www.youtube.com/embed/C_Yq-mD_AMA",
      },
      {
        title: { es: "Video Tutorial Adicional 2", pt: "Vídeo Tutorial Adicional 2" },
        embedUrl: "https://www.youtube.com/embed/C_Yq-mD_AMA",
      },
      {
        title: { es: "Video Tutorial Adicional 3", pt: "Vídeo Tutorial Adicional 3" },
        embedUrl: "https://www.youtube.com/embed/C_Yq-mD_AMA",
      }
    ],
    flashcards: [
        {
          question: { es: "¿Qué es un AVM (Modelo de Valoración Automatizada)?", pt: "O que é um AVM (Modelo de Avaliação Automatizada)?" },
          answer: { es: "Es un algoritmo de IA que estima el valor de una propiedad analizando bases de datos de propiedades comparables, datos de mercado y características del inmueble.", pt: "É um algoritmo de IA que estima o valor de uma propriedade analisando bases de dados de imóveis comparáveis, dados de mercado e características do imóvel." },
          explanation: { es: "Un AVM utiliza técnicas de machine learning, como el análisis de regresión, para encontrar patrones en grandes volúmenes de datos. Considera factores como ventas recientes en la zona, características de la propiedad (m², habitaciones), y datos públicos. Su principal ventaja es la velocidad, ya que puede generar una estimación de valor en segundos, a diferencia de una tasación tradicional que puede tardar días.", pt: "Um AVM utiliza técnicas de machine learning, como a análise de regressão, para encontrar padrões em grandes volumes de dados. Considera fatores como ventas recentes na zona, características da propriedade (m², quartos), e dados públicos. A sua principal vantagem é a velocidade, pois pode gerar uma estimativa de valor em segundos, ao contrário de uma avaliação tradicional que pode demorar dias." }
        },
        {
          question: { es: "¿Qué es un CMA (Análisis Comparativo de Mercado)?", pt: "O que é uma CMA (Análise Comparativa de Mercado)?" },
          answer: { es: "Es un informe que un agente inmobiliario prepara para determinar el precio de una propiedad, comparándola con propiedades similares vendidas recientemente ('comparables') en la misma zona.", pt: "É um relatório que um agente imobiliário prepara para determinar o preço de uma propriedade, comparando-a com imóveis semelhantes vendidos recentemente ('comparáveis') na mesma zona." },
          explanation: { es: "Un CMA es la herramienta fundamental de un agente para fijar un precio. No es una tasación oficial, sino una opinión de valor basada en el mercado. La IA puede automatizar la creación de un CMA, seleccionando los comparables más relevantes y sugiriendo los ajustes de precio necesarios, lo que acelera enormemente el trabajo del agente.", pt: "Uma CMA é a ferramenta fundamental de um agente para fixar um preço. Não é uma avaliação oficial, mas sim uma opinião de valor baseada no mercado. A IA pode automatizar a criação de uma CMA, selecionando os comparáveis mais relevantes e sugerindo os ajustes de preço necessários, o que acelera enormemente o trabalho do agente." }
        },
        {
          question: { es: "Diferencia clave entre un AVM y una tasación tradicional.", pt: "Diferença-chave entre um AVM e uma avaliação tradicional." },
          answer: { es: "Un AVM es una estimación estadística automatizada basada en datos. Una tasación es una opinión de valor realizada por un tasador profesional certificado que incluye una inspección física de la propiedad.", pt: "Um AVM é uma estimativa estatística automatizada baseada em dados. Uma avaliação é uma opinião de valor realizada por um avaliador profissional certificado que inclui uma inspeção física da propriedade." },
          explanation: { es: "Un AVM no 've' la propiedad. No sabe si la cocina está reformada o si las vistas son espectaculares, a menos que se le proporcionen esos datos. Una tasación tradicional sí tiene en cuenta estos factores cualitativos. Por eso, un AVM es una excelente herramienta para una valoración inicial rápida, pero una tasación es a menudo necesaria para procesos formales como una hipoteca.", pt: "Um AVM não 'vê' a propriedade. Não sabe se a cozinha está remodelada ou se as vistas são espetaculares, a menos que esses dados sejam fornecidos. Uma avaliação tradicional tem em conta esses fatores qualitativos. Por isso, um AVM é uma excelente ferramenta para uma avaliação inicial rápida, mas uma avaliação é frequentemente necessária para processos formais como um crédito à habitação." }
        },
        {
          question: { es: "¿Qué son los 'comparables' o 'comps'?", pt: "O que são os 'comparáveis' ou 'comps'?" },
          answer: { es: "Son propiedades vendidas recientemente, lo más similares posible a la propiedad que se está valorando en términos de ubicación, tamaño, características y estado.", pt: "São propriedades vendidas recentemente, o mais semelhantes possível à propriedade que está a ser avaliada em termos de localização, tamanho, características e estado." },
          explanation: { es: "La selección de buenos comparables es el corazón de cualquier valoración. Idealmente, deberían ser del mismo barrio, haberse vendido en los últimos 3-6 meses, y tener un tamaño y número de habitaciones similar. La IA es muy buena seleccionando 'comps' de grandes bases de datos, pero el conocimiento local del agente es crucial para validar que la selección es realmente comparable (ej. no comparar un piso en una calle ruidosa con uno en una calle tranquila, aunque estén cerca).", pt: "A seleção de bons comparáveis é o coração de qualquer avaliação. Idealmente, deveriam ser do mesmo bairro, ter sido vendidos nos últimos 3-6 meses, e ter um tamanho e número de quartos semelhante. A IA é muito boa a selecionar 'comps' de grandes bases de dados, mas o conhecimento local do agente é crucial para validar que a seleção é realmente comparável (ex. não comparar um apartamento numa rua barulhenta com um numa rua tranquila, mesmo que estejam perto)." }
        },
        {
          question: { es: "¿Qué es el 'score de confianza' de un AVM?", pt: "O que é o 'score de confiança' de um AVM?" },
          answer: { es: "Es una puntuación (ej. de 1 a 100) que indica qué tan fiable es la valoración de la IA. Una puntuación alta significa que hay muchos datos de buena calidad.", pt: "É uma pontuação (ex. de 1 a 100) que indica quão fiável é a avaliação da IA. Uma pontuação alta significa que há muitos dados de boa qualidade." },
          explanation: { es: "Un 'score' de confianza bajo no significa que la valoración sea incorrecta, sino que la IA tiene menos certeza. Esto suele ocurrir con propiedades muy únicas (un loft en una antigua fábrica) o en zonas rurales con pocas ventas recientes. Un score alto (+90) se da en zonas urbanas con muchas transacciones de propiedades homogéneas (ej. pisos de 2 habitaciones en un mismo barrio).", pt: "Um 'score' de confiança baixo não significa que a avaliação esteja incorreta, mas que a IA tem menos certeza. Isto acontece geralmente com propriedades muito únicas (um loft numa antiga fábrica) ou em zonas rurais com poucas vendas recentes. Um score alto (+90) ocorre em zonas urbanas com muitas transações de propriedades homogéneas (ex. apartamentos T2 num mesmo bairro)." }
        },
        {
          question: { es: "Menciona 3 fuentes de datos principales para un AVM.", pt: "Mencione 3 fontes de dados principais para um AVM." },
          answer: { es: "1. Registros públicos de la propiedad (precios de venta reales). 2. MLS o portales inmobiliarios. 3. Datos del catastro (metros cuadrados, año de construcción).", pt: "1. Registos públicos da propriedade (preços de venda reais). 2. MLS ou portais imobiliários. 3. Dados do cadastro (metros quadrados, ano de construção)." },
          explanation: { es: "La calidad de un AVM depende de la calidad de sus datos. Los AVM más potentes combinan múltiples fuentes: datos de transacciones cerradas (la fuente más fiable), datos de propiedades actualmente en el mercado (para ver la competencia), datos fiscales y catastrales, e incluso datos geoespaciales (proximidad a parques, transporte, colegios) y demográficos.", pt: "A qualidade de um AVM depende da qualidade dos seus dados. Os AVM mais potentes combinam múltiplas fontes: dados de transações fechadas (a fonte mais fiável), dados de propriedades atualmente no mercado (para ver a concorrência), dados fiscais e cadastrais, e até dados geoespaciais (proximidade a parques, transportes, escolas) e demográficos." }
        },
        {
          question: { es: "¿Qué es el 'análisis de regresión' en la valoración?", pt: "O que é a 'análise de regressão' na avaliação?" },
          answer: { es: "Es una técnica estadística que usan los AVM para determinar la relación entre las características de una propiedad (m², habitaciones) y su precio de venta.", pt: "É uma técnica estatística que os AVM usam para determinar a relação entre as características de uma propriedade (m², quartos) e o seu preço de venda." },
          explanation: { es: "El modelo de regresión analiza miles de ventas pasadas y 'aprende', por ejemplo, que en un barrio determinado, cada metro cuadrado adicional añade, en promedio, 3.000€ al precio, y tener un baño extra añade 15.000€. Cuando valoras una nueva propiedad, el modelo aplica estas relaciones que ha aprendido para estimar su precio.", pt: "O modelo de regressão analisa milhares de vendas passadas e 'aprende', por exemplo, que num determinado bairro, cada metro quadrado adicional acrescenta, em média, 3.000€ ao preço, e ter uma casa de banho extra acrescenta 15.000€. Quando avalia uma nova propriedade, o modelo aplica estas relações que aprendeu para estimar o seu preço." }
        },
        {
          question: { es: "¿Qué es un 'modelo hedónico'?", pt: "O que é um 'modelo hedónico'?" },
          answer: { es: "Es un tipo de modelo de regresión usado en valoración que asume que el precio de una casa es la suma del valor de cada una de sus características individuales (ubicación, tamaño, vistas, etc.).", pt: "É um tipo de modelo de regressão usado na avaliação que assume que o preço de uma casa é a soma do valor de cada uma das suas características individuais (localização, tamanho, vistas, etc.)." },
          explanation: { es: "El modelo hedónico intenta asignar un precio implícito a cada atributo. Por ejemplo, puede determinar que la característica 'vistas al mar' añade un 15% al valor de una propiedad en comparación con una idéntica sin vistas. Los AVM utilizan estos modelos para realizar ajustes precisos entre la propiedad a valorar y sus comparables.", pt: "O modelo hedónico tenta atribuir um preço implícito a cada atributo. Por exemplo, pode determinar que a característica 'vistas para o mar' acrescenta 15% ao valor de uma propriedade em comparação com uma idêntica sem vistas. Os AVM utilizam estes modelos para fazer ajustes precisos entre la propriedade a avaliar e os seus comparáveis." }
        },
        {
          question: { es: "¿Cómo influye la ubicación en el valor?", pt: "Como a localização influencia o valor?" },
          answer: { es: "Es el factor más importante. El valor se determina por el barrio, la calle específica, y la proximidad a servicios (transporte, colegios, parques) y la ausencia de externalidades negativas (ruido).", pt: "É o fator mais importante. O valor é determinado pelo bairro, pela rua específica, e pela proximidade a serviços (transportes, escolas, parques) e pela ausência de externalidades negativas (ruído)." },
          explanation: { es: "La máxima del sector inmobiliario sigue siendo 'ubicación, ubicación, ubicación'. La IA cuantifica esto mediante análisis geoespacial. Un AVM puede asignar un valor positivo por estar a menos de 500 metros de una estación de metro y un valor negativo por estar junto a una autopista. El conocimiento local del agente es clave para matizar estos datos (ej. 'sí, está cerca del metro, pero esa estación tiene mala reputación').", pt: "A máxima do setor imobiliário continua a ser 'localização, localização, localização'. A IA quantifica isto através de análise geoespacial. Um AVM pode atribuir um valor positivo por estar a menos de 500 metros de uma estação de metro e um valor negativo por estar junto a uma autoestrada. O conhecimento local do agente é fundamental para matizar estes dados (ex. 'sim, está perto do metro, mas essa estação tem má reputação')." }
        },
        {
          question: { es: "¿Cómo se 'ajusta' el precio de un comparable?", pt: "Como se 'ajusta' o preço de um comparável?" },
          answer: { es: "Si el comparable es mejor que tu propiedad en algún aspecto (ej. tiene garaje y la tuya no), restas valor a su precio de venta. Si es peor, sumas valor.", pt: "Se o comparável é melhor que a sua propriedade em algum aspeto (ex. tem garagem e a sua não), subtrai valor ao seu preço de venda. Se é pior, soma valor." },
          explanation: { es: "El objetivo es hacer que el comparable sea lo más parecido posible a la propiedad que estás valorando. Si un comparable se vendió por 300.000€ pero tenía una terraza de la que tu piso carece, y estimas que esa terraza vale 20.000€, el precio 'ajustado' del comparable sería 280.000€. La IA realiza estos ajustes automáticamente basándose en sus modelos hedónicos.", pt: "O objetivo é tornar o comparável o mais parecido possível com a propriedade que está a avaliar. Se um comparável foi vendido por 300.000€ mas tinha um terraço que o seu apartamento не tem, e estima que esse terraço vale 20.000€, o preço 'ajustado' do comparável seria 280.000€. A IA realiza estes ajustes automaticamente com base nos seus modelos hedónicos." }
        },
        {
          question: { es: "¿Qué es un 'outlier' o valor atípico en los datos de venta?", pt: "O que é um 'outlier' ou valor atípico nos dados de venda?" },
          answer: { es: "Es una venta que se desvía enormemente del resto (un precio muy alto o muy bajo). La IA debe ser capaz de identificar y a menudo excluir estos datos para no distorsionar la valoración.", pt: "É uma venda que se desvia enormemente do resto (um preço muito alto ou muito baixo). A IA deve ser capaz de identificar e muitas vezes excluir estes dados para não distorcer a avaliação." },
          explanation: { es: "Un 'outlier' podría ser una venta entre familiares a un precio por debajo del mercado, o la venta de un ático de super lujo que no es representativo del resto de pisos del edificio. Si un AVM incluyera estos datos en su análisis de regresión, el resultado sería incorrecto. Los algoritmos de IA utilizan técnicas estadísticas para detectar y ponderar a la baja (o eliminar) estos valores atípicos.", pt: "Um 'outlier' poderia ser uma venda entre familiares a um preço abaixo do mercado, ou a venda de uma penthouse de super luxo que не é representativa do resto dos apartamentos do prédio. Se um AVM incluísse estes dados na sua análise de regressão, o resultado seria incorreto. Os algoritmos de IA utilizam técnicas estatísticas para detetar e ponderar para baixo (ou eliminar) estes valores atípicos." }
        },
        {
          question: { es: "¿Cómo puede la IA analizar la calidad de las reformas de una foto?", pt: "Como a IA pode analisar a qualidade das remodelações de uma foto?" },
          answer: { es: "Mediante 'visión por computador' (Computer Vision). La IA puede identificar si una cocina tiene electrodomésticos de gama alta, encimeras de mármol o un diseño moderno, y asignar un valor a esa reforma.", pt: "Através da 'visão computacional' (Computer Vision). A IA pode identificar se uma cozinha tem eletrodomésticos de gama alta, bancadas de mármore ou um design moderno, e atribuir um valor a essa remodelação." },
          explanation: { es: "Esta es una capacidad avanzada de los AVM más modernos. En lugar de solo tener un campo 'reformado: sí/no', la IA analiza las imágenes del anuncio. Puede reconocer marcas, materiales y estilos, y puntuar la calidad de la reforma de 1 a 10. Esto permite una valoración mucho más precisa que tiene en cuenta la inversión real realizada en la propiedad.", pt: "Esta é uma capacidade avançada dos AVM mais modernos. Em vez de ter apenas um campo 'remodelado: sim/não', a IA analisa as imagens do anúncio. Pode reconocer marcas, materiais e estilos, e pontuar a qualidade da remodelação de 1 a 10. Isto permite uma avaliação muito mais precisa que tem em conta a inversão real realizada na propriedade." }
        },
        {
          question: { es: "¿Qué es el 'sesgo algorítmico' en la valoración?", pt: "O que é o 'viés algorítmico' na avaliação?" },
          answer: { es: "Es el riesgo de que el AVM perpetúe sesgos históricos presentes en los datos, como infravalorar sistemáticamente propiedades en barrios de minorías.", pt: "É o risco de o AVM perpetuar vieses históricos presentes nos dados, como subavaliar sistematicamente propriedades em bairros de minorias." },
          explanation: { es: "Si un AVM se entrena con datos históricos de un mercado donde existía discriminación (consciente o inconsciente), puede 'aprender' esos patrones y replicarlos. Esto es un problema ético y legal muy serio. Las empresas que desarrollan AVM deben auditar constantemente sus modelos para detectar y corregir estos sesgos, asegurando que las valoraciones se basen únicamente en las características objetivas de la propiedad y su ubicación.", pt: "Se um AVM é treinado com dados históricos de um mercado onde existia discriminação (consciente ou inconsciente), pode 'aprender' esses padrões e replicá-los. Isto é um problema ético e legal muito sério. As empresas que desenvolvem AVM devem auditar constantemente os seus modelos para detetar e corrigir estes vieses, garantindo que as avaliações se baseiam unicamente nas características objetivas da propriedade e na sua localização." }
        },
        {
          question: { es: "¿Qué es el 'precio por metro cuadrado' y cuál es su limitación?", pt: "O que é o 'preço por metro quadrado' e qual é a sua limitação?" },
          answer: { es: "Es el precio total dividido por la superficie. Su limitación es que es una media y no tiene en cuenta factores cualitativos como las vistas, el estado o la altura del piso.", pt: "É o preço total dividido pela área. A sua limitação é que é uma média e не tem em conta fatores qualitativos como as vistas, o estado ou a altura do andar." },
          explanation: { es: "El precio por metro cuadrado es una métrica útil para una comparación rápida, pero puede ser engañosa. Un ático reformado con terraza en un edificio puede tener el doble de precio por metro cuadrado que un bajo interior a reformar en el mismo edificio. Los AVM son mucho más sofisticados que esta simple media, ya que ponderan decenas de otras variables.", pt: "O preço por metro quadrado é uma métrica útil para uma comparação rápida, mas pode ser enganadora. Uma penthouse remodelada com terraço num prédio pode ter o dobro do preço por metro quadrado de um rés-do-chão interior para remodelar no mesmo prédio. Os AVM são muito mais sofisticados do que esta simples média, pois ponderam dezenas de outras variáveis." }
        },
        {
          question: { es: "¿Cómo se presenta un rango de valoración a un vendedor con expectativas altas?", pt: "Como se apresenta uma faixa de avaliação a um vendedor com expectativas altas?" },
          answer: { es: "Mostrando los datos del AVM y los comparables de forma objetiva, y explicando que un precio demasiado alto reducirá las visitas y 'quemará' la propiedad en el mercado.", pt: "Mostrando os dados do AVM e os comparáveis de forma objetiva, e explicando que um preço demasiado alto reduzirá as visitas e 'queimará' a propriedade no mercado." },
          explanation: { es: "En lugar de discutir, se usan los datos como un aliado. Se puede decir: 'Entiendo que esperabas X. Mira, estos son los 3 pisos más parecidos al tuyo que se han vendido en los últimos 2 meses, y estos son sus precios. Nuestro análisis sugiere que un precio por encima de Y nos dejará sin visitas. Propongo salir en Y, y si la respuesta es muy fuerte, siempre podemos subir'. La IA proporciona la evidencia objetiva para gestionar las expectativas del cliente.", pt: "Em vez de discutir, usam-se os dados como um aliado. Pode-se dizer: 'Compreendo que esperava X. Veja, estes são os 3 apartamentos mais parecidos com o seu que foram vendidos nos últimos 2 meses, e estes são os seus preços. A nossa análise sugere que um preço acima de Y nos deixará sem visitas. Proponho começar em Y, e se a resposta for muito forte, podemos sempre subir'. A IA fornece a evidência objetiva para gerir as expectativas do cliente." }
        },
        {
          question: { es: "¿Cómo afecta la 'estacionalidad' al valor de una propiedad?", pt: "Como a 'sazonalidade' afeta o valor de uma propriedade?" },
          answer: { es: "La demanda inmobiliaria fluctúa durante el año. Generalmente es más alta en primavera y más baja a finales de año o en pleno verano. La IA puede ajustar sus valoraciones según la época.", pt: "A procura imobiliária flutua durante o ano. Geralmente é mais alta na primavera e mais baixa no final do ano ou em pleno verão. A IA pode ajustar as suas avaliações de acordo com a época." },
          explanation: { es: "Un AVM sofisticado tiene en cuenta la estacionalidad. Puede saber que un chalet con piscina tiene una demanda (y por tanto un valor potencial) mayor si sale al mercado en mayo que si sale en noviembre. Al valorar una propiedad, la IA puede ajustar el precio de un comparable que se vendió en un mes de baja demanda para estimar cuál sería su precio en el mes actual de alta demanda.", pt: "Um AVM sofisticado tem em conta a sazonalidade. Pode saber que uma moradia com piscina tem uma procura (e portanto um valor potencial) maior se for para o mercado em maio do que se for em novembro. Ao avaliar uma propriedade, a IA pode ajustar o preço de um comparável que foi vendido num mês de baixa procura para estimar qual seria o seu preço no mês atual de alta procura." }
        },
        {
          question: { es: "¿Qué es el 'análisis de tendencias de mercado' con IA?", pt: "O que é a 'análise de tendências de mercado' com IA?" },
          answer: { es: "Es el análisis de datos a gran escala para identificar si un mercado local está 'caliente' (subiendo precios), 'frío' (bajando) o 'estable', y a qué velocidad.", pt: "É a análise de dados em grande escala para identificar se um mercado local está 'quente' (preços a subir), 'frio' (a descer) ou 'estável', e a que velocidade." },
          explanation: { es: "La IA puede analizar métricas como el 'tiempo medio en el mercado', el 'porcentaje del precio final sobre el precio de salida' o el 'inventario disponible'. Si el tiempo en el mercado está bajando y los precios finales están por encima del precio de salida, la IA identifica una tendencia alcista. Esta información es crucial para decidir la estrategia de precios: en un mercado caliente se puede ser más agresivo, en uno frío hay que ser más conservador.", pt: "A IA pode analisar métricas como o 'tempo médio no mercado', a 'percentagem do preço final sobre o preço de saída' ou o 'inventário disponível'. Se o tempo no mercado está a diminuir e os preços finais estão acima do preço de saída, a IA identifica uma tendência de alta. Esta informação é crucial para decidir a estratégia de preços: num mercado quente pode-se ser mais agressivo, num frio tem de se ser mais conservador." }
        },
        {
          question: { es: "¿Cómo puede la IA predecir la revalorización futura de una zona?", pt: "Como a IA pode prever a valorização futura de uma zona?" },
          answer: { es: "Cruzando datos inmobiliarios con datos alternativos como la apertura de nuevos negocios, planes urbanísticos, mejoras en el transporte o cambios demográficos.", pt: "Cruzando dados imobiliários com dados alternativos como a abertura de novos negócios, planos urbanísticos, melhorias nos transportes ou mudanças demográficas." },
          explanation: { es: "Este es un uso del 'análisis predictivo'. Un algoritmo de IA puede detectar que en los últimos 5 años, siempre que se ha anunciado una nueva línea de metro, los precios en un radio de 1 km han subido un 15% en los 2 años siguientes. Si el ayuntamiento anuncia una nueva estación en un barrio, la IA puede aplicar este patrón y predecir una futura revalorización, identificando una oportunidad de inversión antes de que sea obvia.", pt: "Este é um uso da 'análise preditiva'. Um algoritmo de IA pode detetar que nos últimos 5 anos, sempre que foi anunciada uma nova linha de metro, os preços num raio de 1 km subiram 15% nos 2 anos seguintes. Se a câmara municipal anuncia uma nova estação num bairro, a IA pode aplicar este padrão e prever uma futura valorização, identificando uma oportunidade de investimento antes que seja óbvia." }
        },
        {
          question: { es: "¿Qué son los 'datos no estructurados' en la valoración?", pt: "O que são 'dados não estruturados' na avaliação?" },
          answer: { es: "Son datos que no están en un formato de tabla, como las fotos de una propiedad, los comentarios en un anuncio o la descripción en texto libre.", pt: "São dados que não estão num formato de tabela, como as fotos de uma propriedade, os comentários num anúncio ou a descrição em texto livre." },
          explanation: { es: "Los AVM tradicionales se basaban en datos estructurados (precio, m², etc.). La IA moderna puede analizar datos no estructurados. Usando 'visión por computador' puede analizar la calidad de las fotos. Usando 'Procesamiento de Lenguaje Natural' (PLN) puede 'leer' la descripción y entender si menciona 'recién reformado' o 'cocina de diseño', añadiendo valor por estos conceptos.", pt: "Os AVM tradicionais baseavam-se em dados estruturados (preço, m², etc.). A IA moderna pode analisar dados não estruturados. Usando 'visão computacional' pode analisar a qualidade das fotos. Usando 'Processamento de Linguagem Natural' (PLN) pode 'ler' a descrição e entender se menciona 'recém-remodelado' ou 'cozinha de design', acrescentando valor por estes conceitos." }
        },
        {
          question: { es: "Factor más importante para un comprador familiar, que la IA puede medir.", pt: "Fator mais importante para um comprador familiar, que a IA pode medir." },
          answer: { es: "La proximidad y calidad de los colegios. La IA puede medir la distancia a los colegios mejor valorados e incluirlo como un factor clave en la valoración.", pt: "A proximidade e qualidade das escolas. A IA pode medir a distância às escolas mais bem classificadas e incluí-lo como um fator-chave na avaliação." },
          explanation: { es: "Para muchas familias, el distrito escolar es más importante que los metros cuadrados. Un AVM avanzado puede integrar datos de rankings de colegios. Puede asignar un 'premium' de precio a las propiedades que están en el área de influencia de un colegio muy demandado. Esto permite una valoración mucho más ajustada a la realidad del mercado para ese perfil de comprador.", pt: "Para muitas famílias, o distrito escolar é mais importante que os metros quadrados. Um AVM avançado pode integrar dados de rankings de escolas. Pode atribuir um 'prémio' de preço às propriedades que estão na área de influência de uma escola muito procurada. Isto permite uma avaliação muito mais ajustada à realidade do mercado para esse perfil de comprador." }
        },
        {
          question: { es: "¿Cómo se valora un 'activo intangible' como el 'encanto' o el 'carácter'?", pt: "Como se avalia um 'ativo intangível' como o 'charme' ou o 'caráter'?" },
          answer: { es: "La IA lo infiere indirectamente. Analiza si las descripciones de propiedades con términos como 'con encanto', 'histórico' o 'vigas vistas' se venden a un precio superior al que justificarían solo sus metros cuadrados.", pt: "A IA infere-o indiretamente. Analisa se as descrições de propriedades com termos como 'com charme', 'histórico' ou 'vigas expostas' são vendidas a um preço superior ao que os seus metros quadrados por si só justificariam." },
          explanation: { es: "Esto es difícil, pero la IA puede encontrar correlaciones. Si consistentemente, en un barrio, los pisos en edificios 'catalogados' o 'regios' se venden por un 10% más que otros de igual tamaño y estado, el modelo puede aprender a aplicar este 'premium por encanto' cuando valora una propiedad con esas características, cuantificando algo que antes era puramente subjetivo.", pt: "Isto é difícil, mas a IA pode encontrar correlações. Se consistentemente, num bairro, os apartamentos em edifícios 'classificados' ou 'senhoriais' são vendidos por 10% mais do que outros de igual tamanho e estado, o modelo pode aprender a aplicar este 'prémio por charme' quando avalia uma propriedade com essas características, quantificando algo que antes era puramente subjetivo." }
        },
        {
          question: { es: "¿Qué es el 'curb appeal'?", pt: "O que é 'curb appeal'?" },
          answer: { es: "Es el atractivo de una propiedad vista desde la calle. La primera impresión que causa su fachada, jardín y entrada.", pt: "É o atrativo de uma propriedade vista da rua. A primeira impressão causada pela sua fachada, jardim e entrada." },
          explanation: { es: "Un buen 'curb appeal' (atractivo desde la acera) es fundamental para atraer a los compradores. Incluye una fachada bien pintada, un jardín cuidado, una puerta de entrada atractiva, etc. La IA puede analizar la foto principal de un anuncio y darle una puntuación de 'curb appeal', e incluso sugerir mejoras (ej. 'sugerencia: pintar la puerta de otro color', 'añadir plantas en la entrada').", pt: "Um bom 'curb appeal' (atrativo a partir do passeio) é fundamental para atrair os compradores. Inclui uma fachada bem pintada, um jardim cuidado, uma porta de entrada atraente, etc. A IA pode analisar a foto principal de um anúncio e dar-lhe uma pontuação de 'curb appeal', e até sugerir melhorias (ex. 'sugestão: pintar a porta de outra cor', 'adicionar plantas na entrada')." }
        },
        {
          question: { es: "¿Cómo puede la IA ayudar a valorar propiedades 'off-market'?", pt: "Como a IA pode ajudar a avaliar propriedades 'off-market'?" },
          answer: { es: "Utilizando sus modelos predictivos para estimar el valor de cualquier propiedad, aunque no esté a la venta, basándose en sus características (del catastro) y en las ventas recientes de su entorno.", pt: "Utilizando os seus modelos preditivos para estimar o valor de qualquer propriedade, mesmo que não esteja à venda, com base nas suas características (do cadastro) e nas vendas recentes na sua vizinhança." },
          explanation: { es: "Un agente puede querer contactar al propietario de una casa que no está en venta. Antes de hacerlo, necesita tener una idea de su valor. Puede introducir la dirección en un AVM. La IA buscará los datos públicos de esa propiedad (m², año, etc.) y aplicará su modelo de valoración basado en las ventas de la zona para dar una estimación. Esto permite al agente iniciar la conversación con el propietario con una base de datos sólida.", pt: "Um agente pode querer contactar o proprietário de uma casa que não está à venda. Antes de o fazer, precisa de ter uma ideia do seu valor. Pode introduzir a morada num AVM. A IA procurará os dados públicos dessa propriedade (m², ano, etc.) e aplicará o seu modelo de avaliação baseado nas vendas da zona para dar uma estimativa. Isto permite ao agente iniciar a conversa com o proprietário com uma base de dados sólida." }
        },
        {
          question: { es: "Limitación principal de los AVM en mercados muy volátiles.", pt: "Limitação principal dos AVM em mercados muito voláteis." },
          answer: { es: "Los AVM se basan en datos históricos. En un mercado que cambia muy rápido (subiendo o bajando bruscamente), los datos de ventas de hace 3 meses pueden no ser ya representativos del valor actual.", pt: "Os AVM baseiam-se em dados históricos. Num mercado que muda muito rapidamente (a subir ou a descer bruscamente), os dados de vendas de há 3 meses podem já não ser representativos do valor atual." },
          explanation: { es: "Este es un punto donde la experiencia del agente es crucial. Si el mercado ha caído un 10% en el último mes, el AVM, basado en datos de los últimos 6 meses, puede dar una valoración demasiado optimista. El agente debe ser capaz de interpretar el resultado del AVM y ajustarlo a la baja con su conocimiento en tiempo real del pulso del mercado.", pt: "Este é um ponto onde a experiência do agente é crucial. Se o mercado caiu 10% no último mês, o AVM, baseado em dados dos últimos 6 meses, pode dar uma avaliação demasiado otimista. O agente deve ser capaz de interpretar o resultado do AVM e ajustá-lo para baixo com o seu conhecimento em tempo real do pulso do mercado." }
        },
        {
          question: { es: "¿Puede un AVM valorar una propiedad sobre plano?", pt: "Pode um AVM avaliar uma propriedade em planta?" },
          answer: { es: "Sí, si se le proporcionan todos los datos del proyecto: planos, memoria de calidades, ubicación exacta y precios de propiedades de obra nueva comparables.", pt: "Sim, se lhe forem fornecidos todos os dados do projeto: plantas, caderno de encargos, localização exata e preços de propriedades de construção nova comparáveis." },
          explanation: { es: "La valoración sobre plano es más compleja porque no hay un bien físico que inspeccionar. Un AVM avanzado puede estimar su valor comparándolo con otras promociones de obra nueva en la zona y ajustando el precio según la reputación del promotor, la calidad de los acabados prometidos y la fecha de entrega prevista. Es una herramienta muy útil para promotores que necesitan fijar los precios de una nueva promoción.", pt: "A avaliação em planta é mais complexa porque não há um bem físico para inspecionar. Um AVM avançado pode estimar o seu valor comparando-o com outras promoções de construção nova na zona e ajustando o preço de acordo com a reputação do promotor, a qualidade dos acabamentos prometidos e a data de entrega prevista. É uma ferramenta muito útil para promotores que precisam de fixar os preços de uma nova promoção." }
        },
        {
          question: { es: "¿Cómo se utiliza la IA para crear un 'mapa de calor' de precios?", pt: "Como se utiliza a IA para criar um 'mapa de calor' de preços?" },
          answer: { es: "La IA procesa miles de datos de ventas y los representa visualmente en un mapa, usando colores (ej. del verde, más barato, al rojo, más caro) para mostrar el precio por metro cuadrado en diferentes calles o barrios.", pt: "A IA processa milhares de dados de vendas e representa-os visualmente num mapa, usando cores (ex. do verde, mais barato, ao vermelho, mais caro) para mostrar o preço por metro quadrado em diferentes ruas ou bairros." },
          explanation: { es: "Un mapa de calor es una forma muy intuitiva de entender un mercado local. Permite a un agente y a su cliente ver de un vistazo qué calles son las más cotizadas o dónde están las 'islas' de oportunidad con precios más bajos. Es una herramienta de comunicación visual muy potente para justificar una valoración o para ayudar a un comprador a entender la geografía de precios de una ciudad.", pt: "Um mapa de calor é uma forma muito intuitiva de entender um mercado local. Permite a um agente e ao seu cliente ver rapidamente que ruas são as mais cotadas ou onde estão as 'ilhas' de oportunidade com preços mais baixos. É uma ferramenta de comunicação visual muito potente para justificar uma avaliação ou para ajudar um comprador a entender a geografia de preços de uma cidade." }
        },
        {
          question: { es: "¿Qué es el 'valor de alquiler' estimado por un AVM?", pt: "O que é o 'valor de arrendamento' estimado por um AVM?" },
          answer: { es: "Es una estimación de la renta mensual que una propiedad podría generar, basada en los precios de alquiler de propiedades comparables en la misma zona.", pt: "É uma estimativa da renda mensal que uma propriedade poderia gerar, baseada nos preços de arrendamento de propriedades comparáveis na mesma zona." },
          explanation: { es: "Además de valorar para la venta, muchos AVM también pueden valorar para el alquiler. Esto es muy útil para clientes inversores. El AVM analiza los alquileres recientes de propiedades similares y estima una renta mensual probable. Esto permite al inversor calcular la rentabilidad bruta anual ( (renta mensual * 12) / precio de compra ) y tomar una decisión de inversión informada.", pt: "Além de avaliar para venda, muitos AVM também podem avaliar para arrendamento. Isto é muito útil para clientes investidores. O AVM analisa os arrendamentos recentes de propriedades semelhantes e estima uma renda mensal provável. Isto permite ao inversor calcular a rentabilidade bruta anual ( (renda mensal * 12) / preço de compra ) e tomar uma decisão de investimento informada." }
        },
        {
          question: { es: "¿Cómo puede la valoración con IA ayudar a captar una propiedad?", pt: "Como a avaliação com IA pode ajudar a angariar uma propriedade?" },
          answer: { es: "Aportando datos objetivos y transparentes a la conversación, lo que genera confianza y posiciona al agente como un experto que no se basa en opiniones, sino en análisis de mercado.", pt: "Fornecendo dados objetivos e transparentes à conversa, o que gera confiança e posiciona o agente como um especialista que não se baseia em opiniões, mas em análises de mercado." },
          explanation: { es: "En la reunión de captación, un agente puede presentar un CMA generado por IA. Puede decir: 'He analizado las 50 últimas ventas en su barrio. La IA, junto con mi experiencia, sugiere este rango de precios por estas razones...'. Esta aproximación basada en datos es mucho más profesional y convincente que simplemente dar un número. Ayuda a alinear las expectativas del vendedor con la realidad del mercado desde el primer día.", pt: "Na reunião de angariação, um agente pode apresentar uma CMA gerada por IA. Pode dizer: 'Analisei as 50 últimas vendas no seu bairro. A IA, juntamente com a minha experiência, sugere esta faixa de preços por estas razões...'. Esta abordagem baseada em dados é muito mais profissional e convincente do que simplesmente dar um número. Ajuda a alinhar as expectativas do vendedor com a realidade do mercado desde o primeiro dia." }
        },
        {
          question: { es: "¿Qué es el 'análisis de liquidez' de una propiedad?", pt: "O que é a 'análise de liquidez' de uma propriedade?" },
          answer: { es: "Es una estimación del tiempo que tardará una propiedad en venderse a un determinado precio. La IA lo calcula analizando el 'tiempo medio en el mercado' de propiedades similares.", pt: "É uma estimativa do tempo que uma propriedade demorará a ser vendida a um determinado preço. A IA calcula-o analisando o 'tempo médio no mercado' de propriedades semelhantes." },
          explanation: { es: "La IA puede crear una curva de 'precio vs. tiempo'. Puede decirle a un vendedor: 'Si ponemos el precio en 300.000€, la probabilidad de venta en 60 días es del 80%. Si lo ponemos en 320.000€, esa probabilidad baja al 30% y el tiempo estimado de venta sube a 150 días'. Esta información es crucial para que el vendedor tome una decisión informada, equilibrando su urgencia por vender con su objetivo de precio.", pt: "A IA pode criar uma curva de 'preço vs. tempo'. Pode dizer a um vendedor: 'Se colocarmos o preço em 300.000€, a probabilidade de venda em 60 dias é de 80%. Se o colocarmos em 320.000€, essa probabilidade desce para 30% e o tempo estimado de venda sobe para 150 dias'. Esta informação é crucial para que o vendedor tome uma decisão informada, equilibrando a sua urgência em vender com o seu objetivo de preço." }
        },
        {
          question: { es: "Menciona una externalidad negativa que un AVM avanzado puede detectar.", pt: "Mencione uma externalidade negativa que um AVM avançado pode detetar." },
          answer: { es: "La proximidad a fuentes de ruido como autopistas, vías de tren o aeropuertos. La IA puede aplicar un ajuste negativo al valor si la propiedad está dentro de un 'área de impacto acústico'.", pt: "A proximidade a fontes de ruído como autoestradas, linhas de comboio ou aeroportos. A IA pode aplicar um ajuste negativo ao valor se a propriedade estiver dentro de uma 'área de impacto acústico'." },
          explanation: { es: "Los AVM modernos pueden integrar capas de datos geoespaciales muy diversas. Además del ruido, pueden detectar la proximidad a vertederos, zonas inundables, o incluso datos sobre la tasa de criminalidad de una calle. Al cuantificar el impacto de estas externalidades negativas, la valoración se vuelve mucho más precisa y realista.", pt: "Os AVM modernos podem integrar camadas de dados geoespaciais muito diversas. Além do ruído, podem detetar la proximidade a aterros, zonas inundáveis, ou até dados sobre la taxa de criminalidade de uma rua. Ao quantificar o impacto destas externalidades negativas, a avaliação torna-se muito mais precisa e realista." }
        },
        {
          question: { es: "Menciona una externalidad positiva que un AVM avanzado puede detectar.", pt: "Mencione uma externalidade positiva que um AVM avançado pode detetar." },
          answer: { es: "La proximidad a un parque, una zona verde o un colegio de prestigio. La IA puede añadir un 'premium' de precio a las propiedades que se benefician de estos activos.", pt: "A proximidade a um parque, uma zona verde ou uma escola de prestígio. A IA pode adicionar um 'prémio' de preço às propriedades que beneficiam destes ativos." },
          explanation: { es: "Similar a las negativas, la IA puede cuantificar el valor de las externalidades positivas. Puede aprender que las propiedades a menos de 5 minutos andando de un gran parque urbano se venden, de media, un 7% más caras. Al aplicar este tipo de ajustes, el AVM captura el 'valor de estilo de vida' de una ubicación, no solo sus datos físicos.", pt: "Semelhante às negativas, a IA pode quantificar o valor das externalidades positivas. Pode aprender que as propriedades a menos de 5 minutos a pé de um grande parque urbano são vendidas, em média, 7% mais caras. Ao aplicar este tipo de ajustes, o AVM captura o 'valor de estilo de vida' de uma localização, não apenas os seus dados físicos." }
        },
        {
          question: { es: "Una propiedad está en una 'calle peatonal'. ¿Cómo lo valora la IA?", pt: "Uma propriedade está numa 'rua pedonal'. Como a IA a avalia?" },
          answer: { es: "Puede ser positivo o negativo según el contexto. Positivo en un centro histórico (menos ruido, más encanto). Negativo si implica problemas de acceso o aparcamiento. La IA necesita datos contextuales para valorarlo correctamente.", pt: "Pode ser positivo ou negativo dependendo do contexto. Positivo num centro histórico (menos ruído, mais charme). Negativo se implica problemas de acesso ou estacionamento. A IA precisa de dados contextuais para o avaliar corretamente." },
          explanation: { es: "Este es un ejemplo de la complejidad de la valoración. Un AVM simple podría no diferenciar. Uno avanzado, analizando el tipo de barrio, podría aprender que en zonas comerciales céntricas, la peatonalización es un plus, mientras que en zonas residenciales puede ser un problema para familias con coche. Aquí el conocimiento del agente para interpretar y matizar la valoración de la IA es fundamental.", pt: "Este é um exemplo da complexidade da avaliação. Um AVM simples poderia não diferenciar. Um avançado, analizando o tipo de bairro, poderia aprender que em zonas comerciais centrais, a pedonalização é uma mais-valia, enquanto em zonas residenciais pode ser um problema para famílias com carro. Aqui o conhecimento do agente para interpretar e matizar a avaliação da IA é fundamental." }
        },
        {
          question: { es: "¿Qué es el 'análisis de sentimiento del barrio'?", pt: "O que é a 'análise de sentimento do bairro'?" },
          answer: { es: "Es el uso de IA para analizar lo que la gente dice de un barrio en redes sociales y reseñas online, para medir su percepción pública (si es 'trendy', 'familiar', 'inseguro', etc.).", pt: "É o uso de IA para analisar o que as pessoas dizem de um bairro nas redes sociais e em avaliações online, para medir a sua perceção pública (se é 'trendy', 'familiar', 'inseguro', etc.)." },
          explanation: { es: "El valor de un barrio no solo depende de datos objetivos, sino también de su 'marca' o reputación. Un AVM de vanguardia puede usar PLN para analizar miles de comentarios online. Si detecta un aumento repentino de menciones positivas sobre los 'nuevos restaurantes' y la 'vida nocturna' de un barrio, puede interpretarlo como una señal temprana de gentrificación y revalorización, ajustando sus proyecciones de precios al alza.", pt: "O valor de um bairro не depende apenas de dados objetivos, mas também da sua 'marca' ou reputação. Um AVM de vanguarda pode usar PLN para analisar milhares de comentários online. Se detetar um aumento súbito de menções positivas sobre os 'novos restaurantes' e a 'vida noturna' de um bairro, pode interpretá-lo como um sinal precoce de gentrificação e valorização, ajustando as suas projeções de preços para cima." }
        },
        {
          question: { es: "¿Cómo se valora la 'eficiencia energética'?", pt: "Como se avalia a 'eficiência energética'?" },
          answer: { es: "La IA puede añadir un 'premium' de precio a las propiedades con un Certificado de Eficiencia Energética de clase A o B, ya que implican un menor coste de vida para el futuro propietario.", pt: "A IA pode adicionar um 'prémio' de preço às propriedades com um Certificado de Eficiência Energética de classe A ou B, uma vez que implicam um menor custo de vida para o futuro proprietário." },
          explanation: { es: "Con el aumento de los costes de la energía, la eficiencia es un factor de valor cada vez más importante. Un AVM puede analizar si las propiedades con alta calificación energética se venden más caras o más rápido. Si encuentra una correlación positiva, aplicará un ajuste de valor al alza para las casas más eficientes, permitiendo al agente usar 'el ahorro en facturas' como un argumento de venta tangible.", pt: "Com o aumento dos custos da energia, a eficiência é um fator de valor cada vez mais importante. Um AVM pode analisar se as propriedades com alta classificação energética são vendidas mais caras ou mais rápido. Se encontrar uma correlação positiva, aplicará um ajuste de valor para cima para as casas mais eficientes, permitindo ao agente usar 'a poupança nas faturas' como um argumento de venda tangível." }
        },
        {
          question: { es: "En un prompt para generar un CMA, ¿por qué es útil incluir los 'puntos débiles'?", pt: "Num prompt para gerar uma CMA, porque é útil incluir os 'pontos fracos'?" },
          answer: { es: "Para que la IA pueda buscar comparables que también compartan esos puntos débiles, haciendo la comparación más justa y la valoración más realista y defendible.", pt: "Para que a IA possa procurar comparáveis que também partilhem esses pontos fracos, tornando a comparação mais justa e a avaliação mais realista e defensável." },
          explanation: { es: "Si estás valorando un piso sin ascensor, lo ideal es compararlo con otros pisos sin ascensor que se hayan vendido. Al incluir '4º sin ascensor' en los puntos débiles del prompt, le estás dando a la IA una instrucción clave para su búsqueda. Esto evita que compare tu propiedad con un 4º con ascensor (que se vendería más caro) y te dé una valoración inflada y poco realista.", pt: "Se está a avaliar um apartamento sem elevador, o ideal é compará-lo com outros apartamentos sem elevador que tenham sido vendidos. Ao incluir '4º sem elevador' nos pontos fracos do prompt, está a dar à IA uma instrução-chave para a sua busca. Isto evita que compare a sua propriedade com um 4º com elevador (que seria vendido mais caro) e lhe dê uma avaliação inflacionada e pouco realista." }
        },
        {
          question: { es: "¿Puede la IA valorar el impacto de una reforma futura?", pt: "Pode a IA avaliar o impacto de uma reforma futura?" },
          answer: { es: "Sí, se puede hacer una valoración 'ARV' (After Repair Value). Le das los datos de la propiedad 'como está' y le pides que la valore 'como si tuviera una cocina y baños nuevos de gama media'.", pt: "Sim, pode-se fazer uma avaliação 'ARV' (After Repair Value). Dá-se-lhe os dados da propriedade 'como está' e pede-se-lhe que a avalie 'como se tivesse uma cozinha e casas de banho novas de gama média'." },
          explanation: { es: "Esto es muy útil para inversores o para vendedores que dudan si reformar antes de vender. La IA calcula dos valores: el actual y el post-reforma. La diferencia entre ambos es el 'valor añadido' por la reforma. Esto permite al cliente tomar una decisión basada en datos sobre si la inversión en la reforma merece la pena en términos de aumento del precio de venta.", pt: "Isto é muito útil para investidores ou para vendedores que hesitam em remodelar antes de vender. A IA calcula dois valores: o atual e o pós-remodelação. A diferença entre ambos é o 'valor acrescentado' pela remodelação. Isto permite ao cliente tomar uma decisão baseada em dados sobre se o investimento na remodelação vale a pena em termos de aumento do preço de venda." }
        },
        {
          question: { es: "¿Qué es la 'depreciación' y cómo la calcula la IA?", pt: "O que é a 'depreciação' e como a IA a calcula?" },
          answer: { es: "Es la pérdida de valor de un edificio con el tiempo debido al desgaste. La IA la calcula usando modelos que tienen en cuenta la antigüedad del inmueble, su estado de mantenimiento y la vida útil de sus componentes.", pt: "É a perda de valor de um edifício com o tempo devido ao desgaste. A IA calcula-a usando modelos que têm em conta a antiguidade do imóvel, o seu estado de manutenção e a vida útil dos seus componentes." },
          explanation: { es: "En la valoración por 'coste de reposición', primero se calcula cuánto costaría construir la propiedad hoy, y luego se le resta la depreciación acumulada. La IA puede automatizar este cálculo. Puede tener datos sobre la vida útil media de tejados, sistemas de fontanería, etc., y aplicar una depreciación más o menos acelerada según la edad y el estado de la propiedad, llegando a una estimación del valor actual del edificio.", pt: "Na avaliação pelo 'custo de reposição', primeiro calcula-se quanto custaria construir a propriedade hoje, e depois subtrai-se a depreciação acumulada. A IA pode automatizar este cálculo. Pode ter dados sobre a vida útil média de telhados, sistemas de canalização, etc., e aplicar uma depreciação mais ou menos acelerada de acordo com a idade e o estado da propriedade, chegando a uma estimativa do valor atual do edifício." }
        },
        {
          question: { es: "¿Cómo puede la IA ayudar a valorar un terreno sin edificar?", pt: "Como a IA pode ajudar a avaliar um terreno não edificado?" },
          answer: { es: "Analizando la normativa urbanística para determinar qué se puede construir ('edificabilidad'), y comparándolo con el precio de venta de otros terrenos con un potencial de desarrollo similar.", pt: "Analisando a regulamentação urbanística para determinar o que pode ser construído ('edificabilidade'), e comparando-o com o preço de venda de outros terrenos com um potencial de desenvolvimento semelhante." },
          explanation: { es: "El valor de un terreno depende de lo que se puede construir en él. La IA puede 'leer' los planes urbanísticos de un ayuntamiento para extraer datos como la 'edificabilidad máxima' (cuántos metros cuadrados se pueden construir) y el 'uso permitido' (residencial, comercial...). Luego, busca ventas de terrenos cercanos con una edificabilidad parecida para establecer un precio por 'metro cuadrado de techo edificable', que es la métrica estándar para valorar suelo.", pt: "O valor de um terreno depende do que se pode construir nele. A IA pode 'ler' os planos urbanísticos de uma câmara municipal para extrair dados como a 'área de construção máxima' (quantos metros quadrados se podem construir) e o 'uso permitido' (residencial, comercial...). Depois, procura vendas de terrenos próximos com uma área de construção semelhante para estabelecer um preço por 'metro quadrado de teto edificável', que é a métrica padrão para avaliar terrenos." }
        },
        {
          question: { es: "Finalmente, ¿la IA reemplazará al tasador o al agente en la valoración?", pt: "Finalmente, a IA substituirá o avaliador ou o agente na avaliação?" },
          answer: { es: "No, los potenciará. La IA es una herramienta increíble para el análisis de datos a gran escala, pero la inspección física, el conocimiento hiperlocal y el juicio profesional del experto humano siguen siendo insustituibles.", pt: "Não, irá potenciá-los. A IA é uma ferramenta incrível para a análise de dados em grande escala, mas a inspeção física, o conhecimento hiperlocal e o julgamento profissional do especialista humano continuam a ser insubstituíveis." },
          explanation: { es: "El futuro es una colaboración 'Hombre-Máquina'. La IA proporciona la base de datos objetiva y los análisis en segundos. El agente o tasador aporta el contexto, la interpretación y el conocimiento de factores intangibles que la IA no puede 'ver'. La combinación de ambos da como resultado una valoración más rápida, precisa y defendible que cualquiera de los dos por separado.", pt: "O futuro é uma colaboração 'Homem-Máquina'. A IA fornece a base de dados objetiva e as análises em segundos. O agente ou avaliador contribui com o contexto, a interpretação e o conhecimento de fatores intangíveis que a IA não consegue 'ver'. A combinação de ambos resulta numa avaliação mais rápida, precisa e defensável do que qualquer um deles isoladamente." }
        }
      ]
};