import { Module } from '../types';

export const module7: Module = {
    id: "7",
    title: { es: "7. Negociación y Cierre Asistido por IA", pt: "7. Negociação e Fecho Assistido por IA" },
    description: { es: "Utiliza la IA para analizar perfiles de clientes, preparar argumentos de negociación y anticipar objeciones para cerrar tratos de forma más efectiva.", pt: "Utilize a IA para analisar perfis de clientes, preparar argumentos de negociação e antecipar objeções para fechar negócios de forma mais eficaz." },
    icon: "assistants",
    hero: {
      title: { es: "Cierra Tratos con Precisión Quirúrgica", pt: "Feche Negócios com Precisão Cirúrgica" },
      subtitle: { es: "Usa la IA como tu copiloto en la fase final de la venta, desde la negociación hasta la firma.", pt: "Use a IA como seu copiloto na fase final da venda, desde a negociação até à assinatura." },
      image: "https://picsum.photos/1200/600?random=7",
    },
    content: {
      learnTitle: { es: "Qué dominarás en este módulo", pt: "O que vai dominar neste módulo" },
      points: [
        { es: "Analizar comunicaciones previas para identificar motivaciones y objeciones del cliente.", pt: "Analisar comunicações prévias para identificar motivações e objeções do cliente." },
        { es: "Generar guiones de negociación y respuestas basadas en datos para defender valoraciones y precios.", pt: "Gerar guiões de negociação e respostas baseadas em dados para defender avaliações e preços." },
        { es: "Redactar contraofertas y términos de cierre de forma rápida y precisa, minimizando errores.", pt: "Redigir contrapropostas e termos de fecho de forma rápida e precisa, minimizando erros." },
      ],
      mediaSrc: "https://picsum.photos/500/300?random=17",
    },
    resources: {
      title: { es: "Herramientas y Plantillas de Negociación", pt: "Ferramentas e Modelos de Negociação" },
      downloads: [
        {
          text: { es: "Plantilla: Análisis de Perfil de Cliente con IA", pt: "Modelo: Análise de Perfil de Cliente com IA" },
          url: "/docs/plantilla_analisis_cliente.pdf"
        },
        {
          text: { es: "Guía: Redacción de Contraofertas con IA", pt: "Guia: Redação de Contrapropostas com IA" },
          url: "/docs/guia_contraofertas_ia.pdf"
        }
      ],
    },
    videos: [{
      title: { es: "Simulación de Negociación: IA vs. Objeciones Comunes", pt: "Simulação de Negociação: IA vs. Objeções Comuns" },
      embedUrl: "https://www.youtube.com/embed/S4_I273y2EY",
    }],
    flashcards: [
      {
        question: { es: "¿Cómo analiza la IA el perfil de un cliente para la negociación?", pt: "Como a IA analisa o perfil de um cliente para a negociação?" },
        answer: { es: "Analizando su historial de comunicación (emails, chats) para detectar patrones, palabras clave y el sentimiento general, identificando así sus principales motivaciones y preocupaciones.", pt: "Analisando o seu histórico de comunicação (e-mails, chats) para detetar padrões, palavras-chave e o sentimento geral, identificando assim as suas principais motivações e preocupações." },
        explanation: { es: "La IA utiliza el Procesamiento de Lenguaje Natural (PLN) para 'leer' todas las interacciones pasadas. Busca palabras repetidas como 'presupuesto', 'urgente', 'colegios', que revelan prioridades. Además, el análisis de sentimiento detecta si el tono del cliente es ansioso, confiado o escéptico, permitiendo al agente adaptar su enfoque. Por ejemplo, si la IA detecta ansiedad sobre el proceso, el agente puede iniciar la negociación con un enfoque más tranquilizador y educativo.", pt: "A IA utiliza o Processamento de Linguagem Natural (PLN) para 'ler' todas as interações passadas. Ela procura por palavras repetidas como 'orçamento', 'urgente', 'escolas', que revelam prioridades. Além disso, a análise de sentimento deteta se o tom do cliente é ansioso, confiante ou cético, permitindo ao agente adaptar a sua abordagem. Por exemplo, se a IA deteta ansiedade em relação ao processo, o agente pode começar a negociação com uma abordagem mais tranquilizadora e educativa." }
      },
      {
        question: { es: "¿Qué es un 'escenario de cierre' simulado con IA?", pt: "O que é um 'cenário de fecho' simulado com IA?" },
        answer: { es: "Es una práctica donde un agente interactúa con un chatbot de IA programado para actuar como un cliente difícil, permitiendo al agente ensayar sus argumentos y respuestas a objeciones comunes.", pt: "É uma prática onde um agente interage com um chatbot de IA que foi programado para atuar como um cliente difícil, permitindo ao agente ensaiar os seus argumentos e respostas a objeções comuns." },
        explanation: { es: "Estas simulaciones son entornos de entrenamiento seguros. Un agente puede configurar la IA para ser un 'comprador agresivo que regatea todo' o un 'vendedor emocionalmente apegado a la casa'. El agente puede entonces practicar sus respuestas, probar diferentes argumentos y recibir feedback de la IA sobre la efectividad de su comunicación. Es como tener un sparring de negociación disponible 24/7.", pt: "Estas simulações são ambientes de treino seguros. Um agente pode configurar a IA para ser um 'comprador agressivo que regateia tudo' ou um 'vendedor emocionalmente ligado à casa'. O agente pode então praticar as suas respostas, testar diferentes argumentos e receber feedback da IA sobre a eficácia da sua comunicação. É como ter um sparring partner de negociação disponível 24/7." }
      },
      {
        question: { es: "¿Cómo ayuda la IA a redactar una contraoferta?", pt: "Como a IA ajuda a redigir uma contraproposta?" },
        answer: { es: "Puede generar un borrador estructurado y profesional que incluya los términos clave, justificaciones basadas en datos de mercado y un tono persuasivo, asegurando claridad y reduciendo errores.", pt: "Pode gerar um rascunho estruturado e profissional que inclua os termos chave, justificações baseadas em dados de mercado e um tom persuasivo, garantindo clareza e reduzindo erros." },
        explanation: { es: "Un agente puede dar a la IA los siguientes datos: 'Precio ofrecido: 290.000€. Precio solicitado: 300.000€. Condiciones: el comprador pide incluir los muebles. Mi contraoferta: 298.000€ sin muebles'. La IA redactará un email o documento formal que justifique el precio con base en datos de mercado (del Módulo 2), explique educadamente por qué no se incluyen los muebles, y mantenga un tono colaborativo para no romper la negociación. Esto acelera el proceso y garantiza una comunicación profesional.", pt: "Um agente pode dar à IA os seguintes dados: 'Preço oferecido: 290.000€. Preço pedido: 300.000€. Condições: o comprador pede para incluir os móveis. Minha contraproposta: 298.000€ sem móveis'. A IA redigirá um e-mail ou documento formal que justifique o preço com base em dados de mercado (do Módulo 2), explique educadamente por que os móveis não estão incluídos e mantenha um tom colaborativo para não quebrar a negociação. Isto acelera o processo e garante uma comunicação profissional." }
      },
      {
        question: { es: "¿Qué son los 'puntos de dolor' (pain points) y cómo los identifica la IA?", pt: "O que são os 'pontos de dor' (pain points) e como a IA os identifica?" },
        answer: { es: "Son los problemas o frustraciones principales del cliente. La IA los identifica analizando el lenguaje emocionalmente cargado o las quejas recurrentes en sus comunicaciones.", pt: "São os problemas ou frustrações principais do cliente. A IA identifica-os analisando a linguagem emocionalmente carregada ou as queixas recorrentes nas suas comunicações." },
        explanation: { es: "Un 'punto de dolor' es la razón fundamental por la que un cliente necesita mudarse, vender o comprar. Puede ser 'falta de espacio', 'largo trayecto al trabajo', 'costes de mantenimiento altos'. La IA detecta estas frases y las clasifica. Saber esto permite al agente enfocar su argumento de negociación en cómo su solución (la propiedad o la oferta) alivia directamente ese 'dolor', haciendo la propuesta mucho más atractiva y personal.", pt: "Um 'ponto de dor' é a razão fundamental pela qual um cliente precisa de se mudar, vender ou comprar. Pode ser 'falta de espaço', 'longo trajeto para o trabalho', 'custos de manutenção elevados'. A IA deteta estas frases e classifica-as. Saber isto permite ao agente focar o seu argumento de negociação em como a sua solução (a propriedade ou a oferta) alivia diretamente essa 'dor', tornando a proposta muito mais atrativa e pessoal." }
      },
      {
        question: { es: "¿Cómo puede la IA predecir el estilo de negociación de un cliente?", pt: "Como a IA pode prever o estilo de negociação de um cliente?" },
        answer: { es: "Analizando la elección de palabras. Un lenguaje directo y basado en cifras sugiere un negociador competitivo; un lenguaje centrado en el consenso y los sentimientos sugiere un estilo colaborativo.", pt: "Analisando a escolha de palavras. Uma linguagem direta e baseada em números sugere um negociador competitivo; uma linguagem centrada no consenso e nos sentimentos sugere um estilo colaborativo." },
        explanation: { es: "La IA puede clasificar el lenguaje en categorías como 'analítico', 'amigable', 'directo' o 'expresivo'. Si un cliente usa constantemente frases como 'el resultado final es', 'necesito un descuento del X%', la IA lo marcará como un negociador competitivo. Si usa frases como 'necesitamos encontrar una solución que funcione para todos' o 'me preocupa que...', será marcado como colaborativo. Esto permite al agente adaptar su propia estrategia: ser más directo con los competitivos o más empático con los colaborativos.", pt: "A IA pode classificar a linguagem em categorias como 'analítico', 'amigável', 'direto' ou 'expressivo'. Se um cliente usa constantemente frases como 'o resultado final é', 'preciso de um desconto de X%', a IA irá marcá-lo como um negociador competitivo. Se usar frases como 'precisamos de encontrar uma solução que funcione para todos' ou 'preocupa-me que...', será marcado como colaborativo. Isto permite ao agente adaptar a sua própria estratégia: ser mais direto com os competitivos ou mais empático com os colaborativos." }
      },
      {
        question: { es: "¿Qué es un 'mapa de motivaciones' generado por IA?", pt: "O que é um 'mapa de motivações' gerado pela IA?" },
        answer: { es: "Es un resumen visual o de texto que la IA crea, destacando las prioridades clave de un cliente (ej. 1. Seguridad del barrio, 2. Presupuesto, 3. Jardín para niños), ordenadas por importancia.", pt: "É um resumo visual ou de texto que a IA cria, destacando as prioridades-chave de um cliente (ex. 1. Segurança do bairro, 2. Orçamento, 3. Jardim para as crianças), ordenadas por importância." },
        explanation: { es: "La IA analiza la frecuencia y el contexto con que un cliente menciona ciertos temas. Si la palabra 'seguridad' aparece 10 veces y 'piscina' solo 2, la IA asigna mayor peso a la seguridad. El 'mapa' final le permite al agente ver de un vistazo qué es lo que realmente importa al cliente. En una negociación, esto es oro: si hay que ceder en algo, es mejor ceder en un punto de baja prioridad (la piscina) para mantenerse firme en lo que es crucial para el cliente (la seguridad o el precio).", pt: "A IA analisa a frequência e o contexto com que um cliente menciona certos temas. Se a palavra 'segurança' aparece 10 vezes e 'piscina' apenas 2, a IA atribui maior peso à segurança. O 'mapa' final permite ao agente ver rapidamente o que realmente importa para o cliente. Numa negociação, isto é ouro: se for preciso ceder em algo, é melhor ceder num ponto de baixa prioridade (a piscina) para se manter firme no que é crucial para o cliente (a segurança ou o preço)." }
      },
      {
        question: { es: "¿Cómo ayuda la IA a identificar al verdadero tomador de decisiones?", pt: "Como a IA ajuda a identificar o verdadeiro decisor?" },
        answer: { es: "Analizando quién hace las preguntas sobre el precio y las condiciones (el decisor lógico) y quién habla de las emociones y el estilo de vida (el influenciador emocional).", pt: "Analisando quem faz as perguntas sobre o preço e as condições (o decisor lógico) e quem fala sobre as emoções e o estilo de vida (o influenciador emocional)." },
        explanation: { es: "En una pareja o familia, a menudo hay roles distintos. La IA puede analizar las transcripciones de las conversaciones. La persona que pregunta '¿Cuál es el IBI anual?' o '¿Es negociable el precio?' suele ser el decisor financiero. La persona que dice 'Imagino a los niños jugando aquí' o 'Me encanta la luz que entra' es el influenciador emocional. Para cerrar el trato, hay que convencer a ambos: al primero con datos y cifras, y al segundo con los beneficios emocionales y de estilo de vida.", pt: "Num casal ou família, muitas vezes existem papéis distintos. A IA pode analisar as transcrições das conversas. A pessoa que pergunta 'Qual é o IMI anual?' ou 'O preço é negociável?' geralmente é o decisor financeiro. A pessoa que diz 'Imagino as crianças a brincar aqui' ou 'Adoro a luz que entra' é o influenciador emocional. Para fechar o negócio, é preciso convencer ambos: o primeiro com dados e números, e o segundo com os benefícios emocionais e de estilo de vida." }
      },
      {
        question: { es: "¿Qué tipo de 'señales de compra' puede detectar la IA en una conversación?", pt: "Que tipo de 'sinais de compra' pode a IA detetar numa conversa?" },
        answer: { es: "El uso de lenguaje posesivo ('mi despacho'), preguntas sobre los siguientes pasos ('¿cómo es el proceso de oferta?'), o preguntas sobre detalles menores ('¿de qué color están pintadas las paredes?').", pt: "O uso de linguagem possessiva ('o meu escritório'), perguntas sobre os próximos passos ('como é o processo de oferta?'), ou perguntas sobre detalhes menores ('de que cor estão pintadas as paredes?')." },
        explanation: { es: "Estas son señales sutiles de que un cliente está pasando de 'evaluar' a 'imaginarse viviendo allí'. La IA está entrenada para identificar este cambio lingüístico. Cuando un cliente empieza a usar pronombres posesivos ('nuestra cocina') o se preocupa por detalles prácticos post-compra ('¿cuánto tardarían en darme las llaves?'), la IA puede marcar esa conversación y alertar al agente de que es un momento ideal para intentar un 'cierre de prueba' o para presentar la oferta formalmente.", pt: "Estes são sinais subtis de que um cliente está a passar de 'avaliar' para 'imaginar-se a viver ali'. A IA é treinada para identificar esta mudança linguística. Quando um cliente começa a usar pronomes possessivos ('a nossa cozinha') ou se preocupa com detalhes práticos pós-compra ('quanto tempo demoraria para me entregarem as chaves?'), a IA pode marcar essa conversa e alertar o agente de que é um momento ideal para tentar um 'fecho de teste' ou para apresentar a oferta formalmente." }
      },
      {
        question: { es: "¿Cómo se usa la IA para adaptar tu comunicación al perfil del cliente?", pt: "Como a IA é usada para adaptar a sua comunicação ao perfil do cliente?" },
        answer: { es: "La IA puede analizar el estilo de comunicación del cliente (ej. formal, informal, directo) y generar borradores de emails o mensajes que imiten ese estilo para crear una mejor sintonía.", pt: "A IA pode analisar o estilo de comunicação do cliente (ex. formal, informal, direto) e gerar rascunhos de e-mails ou mensagens que imitem esse estilo para criar uma melhor sintonia." },
        explanation: { es: "Si la IA detecta que un cliente siempre escribe emails cortos y directos, sin saludos largos, puede sugerir o redactar una respuesta igualmente concisa. Si otro cliente es muy formal y siempre usa 'Estimado Sr. Pérez', la IA recomendará mantener esa formalidad. Este 'espejo' de comunicación, o 'mirroring', es una técnica de rapport muy efectiva que la IA puede automatizar, haciendo que el cliente se sienta más cómodo y comprendido a nivel subconsciente.", pt: "Se a IA deteta que um cliente escreve sempre e-mails curtos e diretos, sem saudações longas, pode sugerir ou redigir uma resposta igualmente concisa. Se outro cliente é muito formal e usa sempre 'Estimado Sr. Silva', a IA recomendará manter essa formalidade. Este 'espelho' de comunicação, ou 'mirroring', é uma técnica de rapport muito eficaz que a IA pode automatizar, fazendo com que o cliente se sinta mais confortável e compreendido a um nível subconsciente." }
      },
      {
        question: { es: "¿Cómo puede un agente usar la IA para justificar un precio de venta ante un comprador escéptico?", pt: "Como pode um agente usar a IA para justificar um preço de venda perante um comprador cético?" },
        answer: { es: "Generando un informe instantáneo con los 3-5 comparables más recientes y relevantes que la IA encuentra en bases de datos, y destacando las características que justifican la diferencia de precio.", pt: "Gerando um relatório instantâneo com os 3-5 comparáveis mais recentes e relevantes que a IA encontra em bases de dados, e destacando as características que justificam a diferença de preço." },
        explanation: { es: "En lugar de decir 'el precio es justo', el agente puede decir: 'Entiendo tu punto. Permíteme mostrarte lo que dice el mercado'. Con un prompt a la IA, puede generar en segundos un resumen: 'Propiedades similares en un radio de 500m se han vendido por X, Y y Z en los últimos 2 meses. La nuestra tiene una reforma más reciente, lo que justifica el 5% extra'. Usar datos objetivos y presentados de forma clara desarma la mayoría de las objeciones basadas en opiniones.", pt: "Em vez de dizer 'o preço é justo', o agente pode dizer: 'Compreendo o seu ponto de vista. Permita-me mostrar-lhe o que o mercado diz'. Com um prompt para a IA, pode gerar em segundos um resumo: 'Imóveis semelhantes num raio de 500m foram vendidos por X, Y e Z nos últimos 2 meses. O nosso tem uma renovação mais recente, o que justifica os 5% extra'. Usar dados objetivos e apresentados de forma clara desarma a maioria das objeções baseadas em opiniões." }
      },
      {
        question: { es: "¿Qué son los 'comparables dinámicos' generados por IA?", pt: "O que são os 'comparáveis dinâmicos' gerados por IA?" },
        answer: { es: "Son propiedades comparables que la IA selecciona y ajusta en tiempo real, ponderando no solo el tamaño y la ubicación, sino también la calidad de las reformas, la antigüedad o las vistas.", pt: "São propriedades comparáveis que a IA seleciona e ajusta em tempo real, ponderando não só o tamanho e a localização, mas também a qualidade das remodelações, a antiguidade ou as vistas." },
        explanation: { es: "Un análisis tradicional puede comparar dos pisos de 80m² como si fueran iguales. La IA va más allá. Puede analizar las fotos de los anuncios para puntuar la 'calidad de la cocina' o la 'luminosidad'. Así, si la propiedad que vendes tiene una cocina nueva y el comparable una de hace 15 años, la IA puede sugerir un ajuste de precio al alza, proporcionando un argumento mucho más sofisticado y difícil de rebatir.", pt: "Uma análise tradicional pode comparar dois apartamentos de 80m² como se fossem iguais. A IA vai mais além. Pode analisar as fotos dos anúncios para pontuar a 'calidade da cozinha' ou a 'luminosidade'. Assim, se a propriedade que está a vender tem uma cozinha nova e o comparável tem uma de há 15 anos, a IA pode sugerir um ajuste de preço para cima, fornecendo um argumento muito mais sofisticado e difícil de refutar." }
      },
      {
        question: { es: "¿Puede la IA crear un argumento visual para defender una valoración?", pt: "Pode a IA criar um argumento visual para defender uma avaliação?" },
        answer: { es: "Sí, puede generar gráficos simples como un mapa de calor de precios de la zona, una gráfica de evolución de precios o una tabla comparativa de características vs. precio.", pt: "Sim, pode gerar gráficos simples como um mapa de calor de preços da zona, um gráfico de evolução de preços ou uma tabela comparativa de características vs. preço." },
        explanation: { es: "Una imagen vale más que mil palabras, especialmente en una negociación. Un agente puede pedir a la IA: 'Crea una tabla comparando mi propiedad con estos tres comparables, destacando en verde las características superiores de la mía'. La IA genera una tabla clara y visual que el agente puede mostrar al cliente en su tablet. Este apoyo visual hace que el argumento del precio sea mucho más fácil de entender y aceptar.", pt: "Uma imagem vale mais que mil palavras, especialmente numa negociação. Um agente pode pedir à IA: 'Cria uma tabela comparando a minha propriedade com estes três comparáveis, destacando a verde as características superiores da minha'. A IA gera uma tabela clara e visual que o agente pode mostrar ao cliente no seu tablet. Este apoio visual torna o argumento do preço muito mais fácil de entender e aceitar." }
      },
      {
        question: { es: "¿Cómo ayuda la IA a destacar los 'activos intangibles' de una propiedad?", pt: "Como a IA ajuda a destacar os 'ativos intangíveis' de uma propriedade?" },
        answer: { es: "Analizando descripciones de propiedades similares que se vendieron rápido para encontrar el lenguaje que mejor describe conceptos como 'luminosidad', 'tranquilidad' o 'encanto'.", pt: "Analisando descrições de propriedades semelhantes que foram vendidas rapidamente para encontrar a linguagem que melhor descreve conceitos como 'luminosidade', 'tranquilidade' ou 'charme'." },
        explanation: { es: "No se puede poner un precio exacto a 'buenas vistas' o 'una calle silenciosa'. Sin embargo, la IA puede analizar miles de anuncios y sus resultados. Puede descubrir, por ejemplo, que los anuncios que usan la frase 'bañado en luz natural' se venden un 10% más rápido que los que solo dicen 'exterior'. La IA puede entonces sugerir al agente usar este lenguaje persuasivo en su negociación para comunicar el valor de estos intangibles de forma efectiva.", pt: "Não se pode colocar um preço exato em 'boas vistas' ou 'uma rua silenciosa'. No entanto, a IA pode analisar milhares de anúncios e os seus resultados. Pode descobrir, por exemplo, que os anúncios que usam a frase 'banhado em luz natural' vendem 10% mais rápido do que os que apenas dizem 'exterior'. A IA pode então sugerir ao agente que use esta linguagem persuasiva na sua negociação para comunicar o valor destes intangíveis de forma eficaz." }
      },
      {
        question: { es: "¿Cómo se usa la análisis predictivo de mercado de la IA en una negociación?", pt: "Como se usa a análise preditiva de mercado da IA numa negociação?" },
        answer: { es: "Para argumentar que, aunque el precio hoy es X, las tendencias indican que la zona se revalorizará, convirtiendo la compra en una excelente inversión a futuro.", pt: "Para argumentar que, embora o preço hoje seja X, as tendências indicam que a zona se irá valorizar, tornando a compra um excelente investimento futuro." },
        explanation: { es: "Si un comprador ofrece un precio bajo, el agente puede usar la IA para contraargumentar no solo con el valor actual, sino con el valor futuro. Puede generar un informe que muestre: 'Los precios en este barrio han subido un 8% anual en los últimos 3 años, y con la nueva línea de metro prevista, se proyecta una subida del 12% el próximo año'. Esto cambia el marco de la negociación de 'un coste' a 'una oportunidad de inversión'.", pt: "Se um comprador oferece um preço baixo, o agente pode usar a IA para contra-argumentar não só com o valor atual, mas com o valor futuro. Pode gerar um relatório que mostre: 'Os preços neste bairro subiram 8% ao ano nos últimos 3 anos, e com a nova linha de metro prevista, projeta-se uma subida de 12% no próximo ano'. Isto muda o enquadramento da negociação de 'um custo' para 'uma oportunidade de investimento'." }
      },
      {
        question: { es: "¿Qué tipo de informe puede generar la IA para rebatir una oferta baja?", pt: "Que tipo de relatório pode a IA gerar para refutar uma oferta baixa?" },
        answer: { es: "Un 'Informe de Justificación de Valor', que incluye comparables, análisis de tendencias de mercado, un listado de mejoras de la propiedad y un coste estimado de oportunidad de perderla.", pt: "Um 'Relatório de Justificação de Valor', que inclui comparáveis, análise de tendências de mercado, uma lista de melhorias da propriedade e um custo estimado de oportunidade de a perder." },
        explanation: { es: "Este informe es un dossier de negociación completo generado en segundos. Un agente le pide a la IA: 'Genera un informe para rebatir una oferta de 250.000€ en la propiedad X, cuyo precio es 270.000€'. La IA compila los datos del mercado, añade una sección valorando las reformas recientes (ej. 'Cocina reformada en 2022: +10.000€ de valor'), y puede incluso añadir un argumento final como: 'Propiedades similares en esta zona no duran más de 15 días en el mercado'.", pt: "Este relatório é um dossiê de negociação completo gerado em segundos. Um agente pede à IA: 'Gera um relatório para refutar uma oferta de 250.000€ na propriedade X, cujo preço é 270.000€'. A IA compila os dados de mercado, adiciona uma secção valorizando as remodelações recentes (ex. 'Cozinha remodelada em 2022: +10.000€ de valor'), e pode até adicionar um argumento final como: 'Imóveis semelhantes nesta zona não duram mais de 15 dias no mercado'." }
      },
      {
        question: { es: "¿Cómo puede la IA encontrar el 'ángulo' de negociación único para una propiedad?", pt: "Como pode a IA encontrar o 'ângulo' de negociação único para uma propriedade?" },
        answer: { es: "Cruzando las características de la propiedad con el perfil del comprador. Si el comprador valora el teletrabajo, la IA sugerirá enfocar la negociación en la 'habitación extra perfecta para una oficina'.", pt: "Cruzando as características da propriedade com o perfil do comprador. Se o comprador valoriza o teletrabalho, a IA sugerirá focar a negociação no 'quarto extra perfeito para um escritório'." },
        explanation: { es: "La IA actúa como un estratega. Conoce la propiedad (tiene una habitación pequeña y luminosa) y conoce al comprador (la IA ha detectado en sus emails que menciona 'trabajo desde casa'). El sistema conecta estos dos puntos y sugiere al agente: 'Enfatiza que la tercera habitación, aunque pequeña, es ideal como despacho en casa, un activo muy valorado post-pandemia'. Este 'ángulo' personalizado hace que el precio parezca más justificado para ese comprador específico.", pt: "A IA atua como um estratega. Conhece a propriedade (tem um quarto pequeno e luminoso) e conhece o comprador (a IA detetou nos seus e-mails que ele menciona 'trabalho a partir de casa'). O sistema conecta estes dois pontos e sugere ao agente: 'Enfatize que o terceiro quarto, embora pequeno, é ideal como escritório em casa, um ativo muito valorizado pós-pandemia'. Este 'ângulo' personalizado faz com que o preço pareça mais justificado para esse comprador específico." }
      }
    ]
};