import { Module } from '../types';

export const module6: Module = {
    id: "6",
    title: { es: "6. Gestión Documental Inteligente", pt: "6. Gestão Documental Inteligente" },
    description: { es: "Usa la IA para redactar contratos, extraer datos de documentos y gestionar toda la burocracia de forma más eficiente.", pt: "Use a IA para redigir contratos, extrair dados de documentos e gerir toda a burocracia de forma mais eficiente." },
    icon: "documents",
    hero: {
      title: { es: "Optimiza tu Papeleo con IA", pt: "Otimize a sua Papelada com IA" },
      subtitle: { es: "Reduce el tiempo dedicado a la gestión de documentos y minimiza errores.", pt: "Reduza o tempo dedicado à gestão de documentos e minimize erros." },
      image: "https://picsum.photos/1200/600?random=6",
    },
    content: {
      learnTitle: { es: "Qué aprenderás a automatizar", pt: "O que vai aprender a automatizar" },
      points: [
        { es: "Redacción de borradores de contratos (arras, alquiler, compraventa) adaptados a cada situación.", pt: "Redação de rascunhos de contratos (sinal, arrendamento, compra e venda) adaptados a cada situação." },
        { es: "Extracción automática de datos clave de documentos escaneados como notas simples, certificados energéticos o escrituras.", pt: "Extração automática de dados-chave de documentos digitalizados como certidões de registo predial, certificados energéticos ou escrituras." },
        { es: "Creación de resúmenes en lenguaje claro de documentos legales complejos para facilitar la comprensión del cliente.", pt: "Criação de resumos em linguagem clara de documentos legais complexos para facilitar a compreensão do cliente." },
        { es: "Análisis de cláusulas para identificar riesgos potenciales o términos no estándar.", pt: "Análise de cláusulas para identificar riscos potenciais ou termos não padronizados." },
        { es: "Gestión de flujos de trabajo documentales, desde la oferta hasta la firma digital.", pt: "Gestão de fluxos de trabalho documentais, desde a oferta até à assinatura digital." }
      ],
    },
    resources: {
      title: { es: "Recursos del Módulo", pt: "Recursos do Módulo" },
      downloads: [],
    },
    videos: [{
      title: { es: "Tutorial: Firmas Digitales en el Sector Inmobiliario", pt: "Tutorial: Assinaturas Digitais no Setor Imobiliário" },
      embedUrl: "https://www.youtube.com/embed/5aJUnp4a6_E",
    }],
    flashcards: [
        {
          question: { es: "¿Qué es la gestión documental inteligente?", pt: "O que é a gestão documental inteligente?" },
          answer: { es: "Es el uso de IA para automatizar la creación, análisis, clasificación y gestión de documentos, reduciendo el trabajo manual y los errores.", pt: "É o uso de IA para automatizar a criação, análise, classificação e gestão de documentos, reduzindo o trabalho manual e os erros." },
          explanation: { es: "La gestión documental tradicional es manual, lenta y propensa a errores. La versión 'inteligente' utiliza tecnologías como la IA y el Machine Learning para transformar el proceso. En lugar de leer manualmente cada documento, la IA puede 'entender' el contenido, extraer datos clave (como nombres, fechas, precios), clasificar el documento (contrato, nota simple, etc.) y almacenarlo correctamente. Esto no solo ahorra cientos de horas, sino que también crea una base de datos estructurada y fácilmente consultable a partir de documentos no estructrados.", pt: "A gestão documental tradicional é manual, lenta e propensa a erros. A versão 'inteligente' utiliza tecnologias como a IA e o Machine Learning para transformar o processo. Em vez de ler manualmente cada documento, a IA pode 'entender' o conteúdo, extrair dados-chave (como nomes, datas, preços), classificar o documento (contrato, certidão, etc.) e armazená-lo corretamente. Isto não só poupa centenas de horas, como também cria uma base de dados estruturada e facilmente consultável a partir de documentos não estruturados." }
        },
        {
          question: { es: "¿Principal ventaja de la IA en la redacción de contratos?", pt: "Principal vantagem da IA na redação de contratos?" },
          answer: { es: "La velocidad y la personalización. Puede generar un borrador de contrato adaptado a una situación específica en segundos, basándose en plantillas y cláusulas pre-aprobadas.", pt: "A velocidade e a personalização. Pode gerar um rascunho de contrato adaptado a uma situação específica em segundos, com base em modelos e cláusulas pré-aprovadas." },
          explanation: { es: "En lugar de copiar y pegar de un contrato anterior y arriesgarse a dejar datos incorrectos, un agente puede dar a la IA los parámetros: 'Genera un contrato de arras para la propiedad X, con el comprador Y, precio Z y fecha de firma W'. La IA utiliza una plantilla validada legalmente y rellena los campos correctos. Además, puede sugerir o añadir cláusulas específicas según el caso (ej. 'cláusula de venta sujeta a financiación'), asegurando que el contrato sea robusto y adaptado.", pt: "Em vez de copiar e colar de um contrato anterior e arriscar-se a deixar dados incorretos, um agente pode dar à IA os parâmetros: 'Gere um contrato-promessa para o imóvel X, com o comprador Y, preço Z e data de escritura W'. A IA utiliza um modelo legalmente validado e preenche os campos corretos. Além disso, pode sugerir ou adicionar cláusulas específicas conforme o caso (ex. 'cláusula de venda sujeita a financiamento'), garantindo que o contrato seja robusto e adaptado." }
        },
        {
          question: { es: "¿Qué es un 'contrato de arras'?", pt: "O que é um 'contrato de arras'?" },
          answer: { es: "Es un preacuerdo privado entre comprador y vendedor donde se entrega una señal económica para reservar la propiedad y fijar las condiciones de la futura compraventa.", pt: "É um pré-acordo privado entre comprador e vendedor onde se entrega um sinal económico para reservar o imóvel e fixar as condições da futura compra e venda." },
          explanation: { es: "El contrato de arras (o contrato-promessa de compra e venda em Portugal) es un paso fundamental y legalmente vinculante. Fija el precio final, el plazo para firmar la escritura pública ante notario y las penalizaciones si una de las partes se echa atrás. Generalmente, si el comprador se retira, pierde la señal entregada (las arras). Si es el vendedor quien se retira, debe devolver el doble de la cantidad recibida. Es un contrato que da seguridad jurídica a ambas partes durante el tiempo que transcurre hasta la firma final.", pt: "O contrato-promessa de compra e venda (ou contrato de arras em Espanha) é um passo fundamental e legalmente vinculativo. Fixa o preço final, o prazo para assinar a escritura pública no notário e as penalizações se uma das partes desistir. Geralmente, se o comprador desiste, perde o sinal entregue (as arras). Se for o vendedor a desistir, deve devolver o dobro do valor recebido. É um contrato que dá segurança jurídica a ambas as partes durante o tempo que decorre até à assinatura final." }
        },
        {
          question: { es: "¿Cómo ayuda la IA con un contrato de arras?", pt: "Como a IA ajuda com um contrato de arras?" },
          answer: { es: "Generando un borrador sin errores, asegurando que todas las cláusulas necesarias estén presentes (precio, plazos, penalizaciones) y adaptándolo a particularidades (ej. si está sujeto a hipoteca).", pt: "Gerando um rascunho sem erros, garantindo que todas as cláusulas necessárias estão presentes (preço, prazos, penalizações) e adaptando-o a particularidades (ex. se está sujeito a hipoteca)." },
          explanation: { es: "La IA actúa como un asistente legal. Puede verificar que el borrador cumple con la legislación vigente, incluir cláusulas estándar de protección para ambas partes y, lo más importante, personalizarlo. Por ejemplo, si el comprador necesita financiación, la IA puede añadir una cláusula que anule el contrato sin penalización si el banco no concede la hipoteca en un plazo determinado, protegiendo al comprador y dando transparencia al acuerdo.", pt: "A IA atua como um assistente legal. Pode verificar se o rascunho cumpre a legislação em vigor, incluir cláusulas padrão de proteção para ambas as partes e, o mais importante, personalizá-lo. Por exemplo, se o comprador precisar de financiamento, a IA pode adicionar uma cláusula que anule o contrato sem penalização se o banco não conceder o crédito hipotecário num determinado prazo, protegendo o comprador e dando transparência ao acordo." }
        },
        {
          question: { es: "¿Qué es una 'cláusula abusiva' y cómo la detecta la IA?", pt: "O que é uma 'cláusula abusiva' e como a IA a deteta?" },
          answer: { es: "Es una condición en un contrato que genera un desequilibrio injusto entre las partes. La IA la detecta comparando el contrato con una base de datos de jurisprudencia y cláusulas consideradas abusivas.", pt: "É uma condição num contrato que gera um desequilíbrio injusto entre as partes. A IA deteta-a comparando o contrato com uma base de dados de jurisprudência e cláusulas consideradas abusivas." },
          explanation: { es: "Una cláusula abusiva es aquella no negociada individualmente que, en contra de la buena fe, causa un perjuicio al consumidor. Un ejemplo sería una cláusula en un contrato de alquiler que obliga al inquilino a pagar reparaciones que por ley corresponden al propietario. La IA puede analizar un contrato y marcar estas cláusulas, alertando al agente con un mensaje como: 'Advertencia: La cláusula 5.3 podría considerarse abusiva según la sentencia del Tribunal Supremo de [fecha]'.", pt: "Uma cláusula abusiva é aquela não negociada individualmente que, contra a boa-fé, causa um prejuízo ao consumidor. Um exemplo seria uma cláusula num contrato de arrendamento que obriga o inquilino a pagar reparações que por lei são da responsabilidade do proprietário. A IA pode analisar um contrato e assinalar estas cláusulas, alertando o agente com uma mensagem como: 'Aviso: A cláusula 5.3 pode ser considerada abusiva de acordo com a sentença do Supremo Tribunal de [data]'." }
        },
        {
          question: { es: "¿Qué es un 'smart contract' en el sector inmobiliario?", pt: "O que é um 'smart contract' no setor imobiliário?" },
          answer: { es: "Es un contrato digital basado en blockchain que se ejecuta automáticamente cuando se cumplen ciertas condiciones pre-programadas, sin intermediarios.", pt: "É um contrato digital baseado em blockchain que se executa automaticamente quando certas condições pré-programadas são cumpridas, sem intermediários." },
          explanation: { es: "Imagina un contrato de alquiler que, de forma automática, transfiere la fianza de vuelta al inquilino el día que termina el contrato, siempre y cuando un inspector (o un sensor IoT) verifique que la propiedad no tiene daños. O un contrato de compraventa que libera los fondos al vendedor en el mismo instante en que el registro de la propiedad se actualiza digitalmente. Los 'smart contracts' prometen transacciones más rápidas, seguras y transparentes, reduciendo la necesidad de intermediarios y la burocracia.", pt: "Imagine um contrato de arrendamento que, de forma automática, transfere a caução de volta ao inquilino no dia em que o contrato termina, desde que um inspetor (ou um sensor IoT) verifique que o imóvel não tem danos. Ou um contrato de compra e venda que liberta os fundos para o vendedor no mesmo instante em que o registo predial é atualizado digitalmente. Os 'smart contracts' prometem transações mais rápidas, seguras e transparentes, reduzindo a necessidade de intermediários e a burocracia." }
        },
        {
          question: { es: "¿Qué es el OCR (Reconocimiento Óptico de Caracteres)?", pt: "O que é o OCR (Reconhecimento Ótico de Caracteres)?" },
          answer: { es: "Es una tecnología que convierte imágenes de texto (como un documento escaneado o una foto) en texto digital editable y que la IA puede 'leer' y analizar.", pt: "É uma tecnologia que converte imagens de texto (como um documento digitalizado ou uma foto) em texto digital editável que a IA pode 'ler' e analisar." },
          explanation: { es: "El OCR es el puente entre el mundo físico (papel) y el mundo digital. Cuando escaneas un contrato antiguo, para el ordenador solo es una imagen. No puede buscar texto ni copiar un párrafo. Al pasar ese escaneo por un software de OCR, la tecnología reconoce las formas de las letras y las convierte en texto digital. Este es el primer paso indispensable para que la IA pueda empezar a trabajar con el documento: extraer datos, analizar cláusulas, etc.", pt: "O OCR é a ponte entre o mundo físico (papel) e o mundo digital. Quando digitaliza um contrato antigo, para o computador é apenas uma imagem. Não pode pesquisar texto nem copiar um parágrafo. Ao passar essa digitalização por um software de OCR, a tecnologia reconhece as formas das letras e converte-as em texto digital. Este é o primeiro passo indispensável para que a IA possa começar a trabalhar com o documento: extrair dados, analisar cláusulas, etc." }
        },
        {
          question: { es: "¿Qué información clave extrae la IA de una 'nota simple'?", pt: "Que informação chave a IA extrai de uma 'nota simples'?" },
          answer: { es: "La IA extrae automáticamente: la descripción de la finca, los titulares (propietarios) y, crucialmente, las cargas o gravámenes (hipotecas, embargos).", pt: "A IA extrai automaticamente: a descrição do imóvel, os titulares (proprietários) e, crucialmente, os ónus ou encargos (hipotecas, penhoras)." },
          explanation: { es: "La nota simple informativa del Registro de la Propiedad es un documento vital. Analizarla manualmente puede ser tedioso. La IA, usando OCR y PLN, escanea el documento y extrae los datos estructurados en segundos. Puede identificar al propietario actual, verificar que los metros cuadrados coinciden con lo que dice el vendedor y, lo más importante, alertar sobre cualquier 'carga' como una hipoteca pendiente de cancelar, un embargo o una servidumbre de paso. Esto acelera drásticamente la 'due diligence' inicial.", pt: "A certidão de registo predial é um documento vital. Analisá-la manualmente pode ser moroso. A IA, usando OCR e PLN, digitaliza o documento e extrai os dados estruturados em segundos. Pode identificar o proprietário atual, verificar se a área coincide com o que o vendedor diz e, o mais importante, alertar sobre quaisquer 'ónus' como uma hipoteca pendente de cancelamento, uma penhora ou uma servidão de passagem. Isto acelera drasticamente a 'due diligence' inicial." }
        },
        {
          question: { es: "¿Cómo acelera la IA la 'due diligence' inmobiliaria?", pt: "Como a IA acelera a 'due diligence' imobiliária?" },
          answer: { es: "Automatizando la revisión de cientos de páginas de documentos (escrituras, licencias, notas simples) para extraer datos, identificar riesgos y verificar la coherencia entre ellos en minutos en lugar de días.", pt: "Automatizando a revisão de centenas de páginas de documentos (escrituras, licenças, certidões) para extrair dados, identificar riscos e verificar a coerência entre eles em minutos em vez de dias." },
          explanation: { es: "La 'due diligence' es el proceso de investigación de una propiedad antes de la compra para confirmar que todo está en orden. Tradicionalmente, es un trabajo intensivo para los abogados. La IA puede revisar todos los documentos del 'data room' y crear un informe de resumen que marque las 'banderas rojas' (red flags), como discrepancias en los metros cuadrados entre el catastro y el registro, licencias de obra caducadas, o cláusulas extrañas en estatutos de la comunidad. Esto no reemplaza al abogado, pero le da una herramienta para trabajar de forma mucho más rápida y segura.", pt: "A 'due diligence' é o processo de investigação de um imóvel antes da compra para confirmar que está tudo em ordem. Tradicionalmente, é um trabalho intensivo para os advogados. A IA pode rever todos os documentos do 'data room' e criar um relatório de resumo que assinale as 'bandeiras vermelhas' (red flags), como discrepâncias na área entre o cadastro e o registo, licenças de obra caducadas, ou cláusulas estranhas nos estatutos do condomínio. Isto não substitui o advogado, mas dá-lhe uma ferramenta para trabalhar de forma muito mais rápida e segura." }
        },
        {
          question: { es: "¿Qué es 'Named Entity Recognition' (NER) en documentos?", pt: "O que é 'Named Entity Recognition' (NER) em documentos?" },
          answer: { es: "Es la capacidad de la IA para identificar y clasificar entidades clave en un texto, como nombres de personas, empresas, direcciones, fechas y cantidades de dinero.", pt: "É a capacidade da IA para identificar e classificar entidades-chave num texto, como nomes de pessoas, empresas, moradas, datas e valores monetários." },
          explanation: { es: "El NER es una tecnología fundamental para la extracción de datos. Cuando la IA lee un contrato, no solo ve texto, sino que identifica que 'Juan Pérez' es una 'Persona', 'Calle Mayor, 5' es una 'Dirección' y '150.000€' es una 'Cantidad Monetaria'. Esto permite a la IA rellenar automáticamente una ficha de la propiedad en el CRM o una base de datos, extrayendo la información relevante de un documento largo sin que un humano tenga que copiarla y pegarla.", pt: "O NER é uma tecnologia fundamental para a extração de dados. Quando a IA lê um contrato, não vê apenas texto, mas identifica que 'João Silva' é uma 'Pessoa', 'Rua Principal, 5' é uma 'Morada' e '150.000€' é uma 'Quantia Monetária'. Isto permite à IA preencher automaticamente uma ficha do imóvel no CRM ou numa base de dados, extraindo a informação relevante de um documento longo sem que um humano tenha de a copiar e colar." }
        },
        {
          question: { es: "¿Qué es una firma digital o electrónica?", pt: "O que é uma assinatura digital ou eletrónica?" },
          answer: { es: "Es un método legalmente vinculante para firmar documentos digitalmente, utilizando tecnología de cifrado para garantizar la autenticidad del firmante y la integridad del documento.", pt: "É um método legalmente vinculativo para assinar documentos digitalmente, utilizando tecnologia de encriptação para garantir a autenticidade do signatário e a integridade do documento." },
          explanation: { es: "Una firma electrónica va mucho más allá de una imagen de tu firma pegada en un PDF. Las plataformas como DocuSign o Signaturit utilizan certificados digitales y criptografía para vincular la identidad de una persona con un documento específico. El proceso registra quién firmó, cuándo, desde qué dirección IP y asegura que el documento no pueda ser alterado después de la firma. En la UE, la regulación eIDAS otorga plena validez jurídica a la firma electrónica cualificada, equiparándola a la firma manuscrita.", pt: "Uma assinatura eletrónica vai muito além de uma imagem da sua assinatura colada num PDF. Plataformas como DocuSign ou Signaturit utilizam certificados digitais e criptografia para vincular a identidade de uma pessoa a um documento específico. O processo regista quem assinou, quando, a partir de que endereço IP e garante que o documento não pode ser alterado após a assinatura. Na UE, o regulamento eIDAS confere plena validade jurídica à assinatura eletrónica qualificada, equiparando-a à assinatura manuscrita." }
        },
        {
          question: { es: "¿Cómo automatiza la IA un flujo de firmas digitales?", pt: "Como a IA automatiza um fluxo de assinaturas digitais?" },
          answer: { es: "Integrándose con plataformas de firma: una vez que un contrato se genera, la IA lo envía automáticamente a las partes para su firma y monitorea el estado, enviando recordatorios si es necesario.", pt: "Integrando-se com plataformas de assinatura: uma vez gerado um contrato, a IA envia-o automaticamente às partes para assinatura e monitoriza o estado, enviando lembretes se necessário." },
          explanation: { es: "Imagina un flujo completo: 1. La IA genera el contrato de alquiler. 2. Automáticamente lo sube a DocuSign y define el orden de los firmantes (primero el inquilino, luego el propietario). 3. Envía el enlace de firma a cada parte. 4. Si el inquilino no firma en 24 horas, la IA le envía un recordatorio por email o SMS. 5. Una vez que todos han firmado, la IA descarga la versión final firmada y la archiva automáticamente en la carpeta correcta del cliente en el CRM. Todo el proceso ocurre sin intervención manual.", pt: "Imagine um fluxo completo: 1. A IA gera o contrato de arrendamento. 2. Automaticamente, carrega-o para o DocuSign e define a ordem dos signatários (primeiro o inquilino, depois o proprietário). 3. Envia o link de assinatura a cada parte. 4. Se o inquilino não assinar em 24 horas, a IA envia-lhe um lembrete por e-mail ou SMS. 5. Assim que todos assinam, a IA descarrega a versão final assinada e arquiva-a automaticamente na pasta correta do cliente no CRM. Todo o processo ocorre sem intervenção manual." }
        },
        {
          question: { es: "¿Cómo ayuda la IA con el cumplimiento del GDPR en la gestión de documentos?", pt: "Como a IA ajuda no cumprimento do RGPD na gestão de documentos?" },
          answer: { es: "Automatizando la identificación y redacción (ocultación) de datos personales sensibles en documentos, y gestionando los plazos de conservación y eliminación de datos.", pt: "Automatizando a identificação e redação (ocultação) de dados pessoais sensíveis em documentos, e gerindo os prazos de conservação e eliminação de dados." },
          explanation: { es: "El GDPR (Reglamento General de Protección de Datos) impone reglas estrictas sobre cómo se manejan los datos personales. La IA ayuda a cumplirlas. Por ejemplo, puede escanear todos tus documentos y encontrar dónde aparece el DNI o la cuenta bancaria de un cliente. Si necesitas compartir un documento con un tercero pero no su DNI, la IA puede 'redactar' (tachar en negro) esa información automáticamente. También puede crear alertas cuando los documentos de un cliente han superado el plazo legal de conservación, sugiriendo su eliminación segura.", pt: "O RGPD (Regulamento Geral sobre a Proteção de Dados) impõe regras estritas sobre como os dados pessoais são manuseados. A IA ajuda a cumpri-las. Por exemplo, pode digitalizar todos os seus documentos e encontrar onde aparece o NIF ou a conta bancária de um cliente. Se precisar de partilhar um documento com um terceiro mas não o seu NIF, a IA pode 'redigir' (tachar a negro) essa informação automaticamente. Também pode criar alertas quando os documentos de um cliente ultrapassam o prazo legal de conservação, sugerindo a sua eliminação segura." }
        },
        {
          question: { es: "¿Qué es el 'versionado de contratos' y cómo lo gestiona la IA?", pt: "O que é o 'versionamento de contratos' e como a IA o gere?" },
          answer: { es: "Es el control de las diferentes versiones de un contrato durante la negociación. La IA puede comparar versiones y resaltar automáticamente los cambios realizados entre una y otra.", pt: "É o controlo das diferentes versões de um contrato durante a negociação. A IA pode comparar versões e destacar automaticamente as alterações feitas entre uma e outra." },
          explanation: { es: "En una negociación, un contrato puede tener múltiples versiones (v1, v2, v3...). Es fácil perderse qué cambios se hicieron en cada una. La IA puede tomar dos documentos (la versión del abogado del comprador y la tuya) y generar un 'informe de cambios' que muestre exactamente qué cláusulas se han añadido, eliminado o modificado. Esto ahorra horas de revisión manual y asegura que no se pase por alto ningún cambio importante.", pt: "Numa negociação, um contrato pode ter múltiplas versões (v1, v2, v3...). É fácil perder o rasto das alterações feitas em cada uma. A IA pode pegar em dois documentos (a versão do advogado do comprador e a sua) e gerar um 'relatório de alterações' que mostre exatamente que cláusulas foram adicionadas, eliminadas ou modificadas. Isto poupa horas de revisão manual e garante que nenhuma alteração importante passe despercebida." }
        },
        {
          question: { es: "¿Puede la IA traducir documentos legales inmobiliarios?", pt: "Pode a IA traduzir documentos legais imobiliários?" },
          answer: { es: "Sí, los modelos de IA modernos son muy buenos traduciendo, pero para documentos legales siempre se recomienda una revisión final por un traductor humano o un abogado bilingüe.", pt: "Sim, os modelos de IA modernos são muito bons a traduzir, mas para documentos legais recomenda-se sempre uma revisão final por um tradutor humano ou um advogado bilingue." },
          explanation: { es: "Para un cliente extranjero, poder leer una versión de un contrato en su propio idioma es un gran servicio que genera confianza. La IA puede proporcionar una traducción casi instantánea y de alta calidad. Sin embargo, la terminología legal es extremadamente precisa y un pequeño error puede cambiar el significado de una cláusula. Por lo tanto, la IA es una herramienta excelente para un primer borrador o para la comprensión general, pero el documento final que se firma debe ser revisado por un profesional cualificado.", pt: "Para um cliente estrangeiro, poder ler uma versão de um contrato na sua própria língua é um grande serviço que gera confiança. A IA pode fornecer uma tradução quase instantânea e de alta qualidade. No entanto, a terminologia legal é extremamente precisa e um pequeno erro pode alterar o significado de uma cláusula. Portanto, a IA é uma excelente ferramenta para um primeiro rascunho ou para a compreensão geral, mas o documento final a ser assinado deve ser revisto por um profissional qualificado." }
        },
        {
          question: { es: "¿Cómo puede la IA crear un 'dossier de propiedad' para un cliente?", pt: "Como a IA pode criar um 'dossiê de propriedade' para um cliente?" },
          answer: { es: "Recopilando y unificando automáticamente todos los documentos relevantes de una propiedad (nota simple, certificado energético, planos, fotos) en un único PDF profesional y con marca.", pt: "Compilando e unificando automaticamente todos os documentos relevantes de um imóvel (certidão, certificado energético, plantas, fotos) num único PDF profissional e com a marca da agência." },
          explanation: { es: "Preparar un dossier completo para un comprador interesado lleva tiempo. La IA puede automatizarlo. Un agente puede seleccionar una propiedad en el CRM y hacer clic en 'Generar Dossier'. La IA recopila todos los archivos asociados, puede incluso generar una descripción de marketing (Módulo 5), añadir un mapa de la zona, y compilar todo en un documento bien diseñado con el logo del agente. Este nivel de profesionalismo y rapidez impresiona a los clientes.", pt: "Preparar um dossiê completo para um comprador interessado leva tempo. A IA pode automatizá-lo. Um agente pode selecionar um imóvel no CRM e clicar em 'Gerar Dossiê'. A IA compila todos os ficheiros associados, pode até gerar uma descrição de marketing (Módulo 5), adicionar um mapa da zona, e compilar tudo num documento bem desenhado com o logótipo do agente. Este nível de profissionalismo e rapidez impressiona os clientes." }
        },
        {
          question: { es: "¿Qué es el 'análisis de cláusulas de riesgo'?", pt: "O que é a 'análise de cláusulas de risco'?" },
          answer: { es: "Es el uso de IA para escanear un contrato en busca de cláusulas atípicas, ambiguas o potencialmente problemáticas que podrían generar conflictos legales en el futuro.", pt: "É o uso de IA para digitalizar um contrato em busca de cláusulas atípicas, ambíguas ou potencialmente problemáticas que possam gerar conflitos legais no futuro." },
          explanation: { es: "La IA puede ser entrenada con miles de contratos inmobiliarios para aprender qué es una 'cláusula estándar'. Cuando analiza un nuevo contrato, puede marcar aquellas que se desvían de la norma. Por ejemplo, podría señalar una cláusula de penalización inusualmente alta o un lenguaje vago sobre quién es responsable de ciertas reparaciones. Esta 'revisión de riesgos' automatizada es una red de seguridad para el agente y su cliente.", pt: "A IA pode ser treinada com milhares de contratos imobiliários para aprender o que é uma 'cláusula padrão'. Quando analisa um novo contrato, pode assinalar aquelas que se desviam da norma. Por exemplo, poderia apontar uma cláusula de penalização invulgarmente alta ou uma linguagem vaga sobre quem é responsável por certas reparações. Esta 'revisão de riscos' automatizada é uma rede de segurança para o agente e o seu cliente." }
        },
        {
          question: { es: "¿Cómo mejora la IA la búsqueda de documentos?", pt: "Como a IA melhora a pesquisa de documentos?" },
          answer: { es: "Permitiendo la 'búsqueda semántica'. Puedes buscar por conceptos ('contratos con cláusula COVID') en lugar de solo por palabras clave exactas.", pt: "Permitindo a 'pesquisa semântica'. Pode procurar por conceitos ('contratos com cláusula COVID') em vez de apenas por palavras-chave exatas." },
          explanation: { es: "Una búsqueda tradicional solo encuentra documentos que contienen la palabra exacta que buscas. La búsqueda semántica, impulsada por IA, entiende el significado. Un agente podría buscar 'todos los contratos que tuvieron problemas con la financiación' y la IA encontraría documentos que contengan frases como 'hipoteca denegada', 'préstamo no concedido' o 'sujeto a aprobación bancaria', aunque no contengan la palabra 'problemas'. Esto hace que encontrar información relevante en un gran archivo digital sea increíblemente rápido y eficiente.", pt: "Uma pesquisa tradicional só encontra documentos que contêm a palavra exata que procura. A pesquisa semântica, impulsionada por IA, entende o significado. Um agente poderia procurar 'todos os contratos que tiveram problemas com o financiamento' e a IA encontraria documentos que contenham frases como 'hipoteca recusada', 'empréstimo não concedido' ou 'sujeito a aprovação bancária', mesmo que não contenham a palavra 'problemas'. Isto torna a procura de informação relevante num grande arquivo digital incrivelmente rápida e eficiente." }
        },
        {
          question: { es: "¿Qué es la 'redacción automática' de datos sensibles?", pt: "O que é a 'redação automática' de dados sensíveis?" },
          answer: { es: "Es el proceso en que la IA identifica y tacha automáticamente información confidencial (DNI, cuentas bancarias) antes de compartir un documento.", pt: "É o processo em que a IA identifica e tacha automaticamente informação confidencial (NIF, contas bancárias) antes de partilhar um documento." },
          explanation: { es: "Imagina que necesitas enviar una copia de una escritura a un posible comprador, pero no quieres que vea los datos personales del vendedor. Hacerlo manualmente en un PDF es lento y arriesgado (puedes olvidar algo). La IA puede escanear el documento, identificar todos los datos que has definido como 'sensibles' y aplicar un recuadro negro sobre ellos, generando una versión segura para compartir. Esto es crucial para el cumplimiento del GDPR y la protección de la privacidad.", pt: "Imagine que precisa de enviar uma cópia de uma escritura a um potencial comprador, mas não quer que ele veja os dados pessoais do vendedor. Fazê-lo manualmente num PDF é lento e arriscado (pode esquecer-se de algo). A IA pode digitalizar o documento, identificar todos os dados que definiu como 'sensíveis' e aplicar uma caixa preta sobre eles, gerando uma versão segura para partilhar. Isto é crucial para o cumprimento do RGPD e a proteção da privacidade." }
        },
        {
          question: { es: "¿Qué es un 'flujo de trabajo documental' (document workflow)?", pt: "O que é um 'fluxo de trabalho documental' (document workflow)?" },
          answer: { es: "Es la secuencia de pasos que sigue un documento desde su creación hasta su archivo final (ej. Borrador -> Revisión -> Firma -> Archivo). La IA puede automatizar el paso de una etapa a otra.", pt: "É a sequência de passos que um documento segue desde a sua criação até ao seu arquivo final (ex. Rascunho -> Revisão -> Assinatura -> Arquivo). A IA pode automatizar a passagem de uma etapa para a outra." },
          explanation: { es: "Un flujo de trabajo documental define las reglas del proceso. Por ejemplo: 'Cuando se firma un contrato de arras (evento), crea automáticamente una tarea para el agente para que solicite la documentación para la hipoteca y notifica al departamento de administración'. La IA actúa como el director de orquesta, asegurando que cada documento avance a la siguiente etapa y que las personas adecuadas sean notificadas en el momento adecuado, evitando cuellos de botella y olvidos.", pt: "Um fluxo de trabalho documental define as regras do processo. Por exemplo: 'Quando um contrato-promessa é assinado (evento), cria automaticamente uma tarefa para o agente para que solicite a documentação para o crédito hipotecário e notifica o departamento de administração'. A IA atua como o maestro, garantindo que cada documento avance para a etapa seguinte e que as pessoas certas sejam notificadas no momento certo, evitando estrangulamentos e esquecimentos." }
        },
        {
          question: { es: "¿Qué es blockchain y cómo se aplica a los documentos inmobiliarios?", pt: "O que é blockchain e como se aplica aos documentos imobiliários?" },
          answer: { es: "Es una base de datos digital, descentralizada e inmutable. Se aplica para crear un registro de la propiedad (título) que es extremadamente seguro, transparente y a prueba de fraudes.", pt: "É uma base de dados digital, descentralizada e imutável. Aplica-se para criar um registo de propriedade que é extremamente seguro, transparente e à prova de fraude." },
          explanation: { es: "Imagina un libro de contabilidad digital que, en lugar de estar en un solo ordenador, está copiado en miles de ellos. Cada vez que se añade una transacción (un 'bloque'), se vincula criptográficamente a la anterior, creando una 'cadena' (blockchain). Cambiar un bloque antiguo es prácticamente imposible sin alterar toda la cadena y ser detectado por la red. Aplicado al registro de la propiedad, esto podría significar que la historia completa de una casa (quién la poseyó, cuándo se vendió, si tiene cargas) estaría en un registro digital inviolable, eliminando fraudes y simplificando drásticamente las transferencias.", pt: "Imagine um livro de registos digital que, em vez de estar num único computador, está copiado em milhares deles. Cada vez que se adiciona uma transação (um 'bloco'), ela é ligada criptograficamente à anterior, criando uma 'cadeia' (blockchain). Alterar um bloco antigo é praticamente impossível sem alterar toda a cadeia e ser detetado pela rede. Aplicado ao registo de propriedade, isto poderia significar que a história completa de uma casa (quem a possuiu, quando foi vendida, se tem ónus) estaria num registo digital inviolável, eliminando fraudes e simplificando drasticamente as transferências." }
        },
        {
            question: { es: "¿Qué es una 'Nota de Encargo' o 'Mandato de Venta'?", pt: "O que é uma 'Nota de Encargo' ou 'Mandato de Venda'?" },
            answer: { es: "Es el contrato que formaliza la relación entre el propietario de un inmueble y la agencia inmobiliaria, otorgándole a esta última la autorización para comercializar la propiedad.", pt: "É o contrato que formaliza a relação entre o proprietário de um imóvel e a agência imobiliária, conferindo a esta última a autorização para comercializar a propriedade." },
            explanation: { es: "Este documento es fundamental ya que establece los términos del servicio: los honorarios del agente, el precio de venta acordado, la duración del mandato (si es en exclusiva o no) y las obligaciones de ambas partes. La IA puede generar un borrador de este documento clave, personalizándolo con los datos del propietario y la propiedad, y asegurando que incluya todas las cláusulas legales necesarias para proteger al agente.", pt: "Este documento é fundamental, pois estabelece os termos do serviço: os honorários do agente, o preço de venda acordado, a duração do mandato (se é exclusivo ou não) e as obrigações de ambas as partes. A IA pode gerar um rascunho deste documento-chave, personalizando-o com os dados do proprietário e do imóvel, e garantindo que inclua todas as cláusulas legais necessárias para proteger o agente." }
        },
        {
            question: { es: "¿Cómo ayuda la IA a analizar un Certificado de Eficiencia Energética?", pt: "Como a IA ajuda a analisar um Certificado de Eficiência Energética?" },
            answer: { es: "Extrayendo automáticamente la calificación energética (A, B, C...), el consumo de energía y las emisiones de CO2, y resumiendo las recomendaciones de mejora.", pt: "Extraindo automaticamente a classificação energética (A, B, C...), o consumo de energia e as emissões de CO2, e resumindo as recomendações de melhoria." },
            explanation: { es: "Un certificado energético puede ser denso. La IA, mediante OCR, lee el documento y extrae los datos más relevantes. Puede presentar un resumen claro al agente: \"Calificación E. Potencial de mejora a C con una inversión en ventanas\". Esta información es útil para el marketing de la propiedad y para asesorar al comprador sobre futuros costes o mejoras.", pt: "Um certificado energético pode ser denso. A IA, através de OCR, lê o documento e extrai os dados mais relevantes. Pode apresentar um resumo claro ao agente: \"Classificação E. Potencial de melhoria para C com um investimento em janelas\". Esta informação é útil para o marketing do imóvel e para aconselhar o comprador sobre futuros custos ou melhorias." }
        },
        {
            question: { es: "¿Qué es la 'verificación de identidad' (KYC) con IA?", pt: "O que é a 'verificação de identidade' (KYC) com IA?" },
            answer: { es: "Es el uso de IA para verificar automáticamente la identidad de un cliente (Know Your Customer), comparando su documento de identidad con una foto o vídeo en tiempo real para prevenir el fraude.", pt: "É o uso de IA para verificar automaticamente a identidade de um cliente (Know Your Customer), comparando o seu documento de identidade com uma foto ou vídeo em tempo real para prevenir a fraude." },
            explanation: { es: "En operaciones inmobiliarias, es crucial cumplir con las normativas anti-blanqueo de capitales (AML). Las herramientas de IA pueden automatizar este proceso: el cliente sube una foto de su DNI y se hace un selfie; la IA verifica la autenticidad del documento, compara la foto con el selfie (prueba de vida) y comprueba que la persona no esté en listas de sanciones internacionales. Esto agiliza el 'onboarding' de clientes y asegura el cumplimiento normativo.", pt: "Em operações imobiliárias, é crucial cumprir as normativas de combate à lavagem de dinheiro (AML). As ferramentas de IA podem automatizar este processo: o cliente carrega uma foto do seu documento de identificação e tira uma selfie; a IA verifica a autenticidade do documento, compara a foto com a selfie (prova de vida) e verifica se a pessoa não está em listas de sanções internacionais. Isto agiliza o 'onboarding' de clientes e garante o cumprimento normativo." }
        },
        {
            question: { es: "¿Cómo puede la IA resumir una escritura de propiedad para un cliente?", pt: "Como a IA pode resumir uma escritura de propriedade para um cliente?" },
            answer: { es: "Analizando el denso lenguaje legal del documento y generando un resumen en lenguaje claro que destaca los puntos más importantes: quiénes son los propietarios, qué propiedad se describe y si tiene cargas.", pt: "Analisando a densa linguagem jurídica do documento e gerando um resumo em linguagem clara que destaca os pontos mais importantes: quem são os proprietários, que propriedade é descrita e se tem ónus." },
            explanation: { es: "Las escrituras son complejas y pueden intimidar a un cliente. Un agente puede usar la IA para generar un resumen fácil de entender: \"En resumen, este documento confirma que Juan y María son los únicos dueños del piso en Calle Mayor, 5, y que actualmente no tiene ninguna hipoteca pendiente\". Esto aporta un gran valor al cliente, generando confianza y demostrando profesionalidad.", pt: "As escrituras são complexas e podem intimidar um cliente. Um agente pode usar a IA para gerar um resumo fácil de entender: \"Em resumo, este documento confirma que João e Maria são os únicos proprietários do apartamento na Rua Principal, 5, e que atualmente não tem nenhuma hipoteca pendente\". Isto agrega grande valor ao cliente, gerando confiança e demonstrando profissionalismo." }
        },
        {
            question: { es: "¿Qué es la 'coherencia documental' y cómo la verifica la IA?", pt: "O que é a 'coerência documental' e como a IA a verifica?" },
            answer: { es: "Es asegurarse de que los datos clave (m², linderos, propietario) son los mismos en todos los documentos (catastro, registro, escritura). La IA lo verifica extrayendo los datos de cada documento y comparándolos automáticamente.", pt: "É garantir que os dados-chave (m², limites, proprietário) são os mesmos em todos os documentos (cadastro, registo, escritura). A IA verifica isso extraindo os dados de cada documento e comparando-os automaticamente." },
            explanation: { es: "Una de las mayores fuentes de problemas legales son las discrepancias entre documentos. La IA puede leer la nota simple, la ficha catastral y la escritura, extraer los metros cuadrados de cada una y alertar al agente si no coinciden: \"Alerta: El catastro indica 85 m², pero la nota simple registra 80 m²\". Esta detección temprana permite resolver el problema antes de que se convierta en un obstáculo para la venta.", pt: "Uma das maiores fontes de problemas legais são as discrepâncias entre documentos. A IA pode ler a certidão de registo predial, a ficha cadastral e a escritura, extrair a área de cada uma e alertar o agente se não coincidirem: \"Alerta: O cadastro indica 85 m², mas a certidão de registo predial regista 80 m²\". Esta deteção precoce permite resolver o problema antes que se torne um obstáculo para a venda." }
        },
        {
            question: { es: "¿Puede la IA ayudar a redactar el texto de una 'hoja de visita'?", pt: "Pode a IA ajudar a redigir o texto de uma 'ficha de visita'?" },
            answer: { es: "Sí, puede generar un texto estándar que incluya los datos de la propiedad, del visitante, y la cláusula de reconocimiento de honorarios en caso de que el cliente compre la propiedad por su cuenta.", pt: "Sim, pode gerar um texto padrão que inclua os dados do imóvel, do visitante, e a cláusula de reconhecimento de honorários caso o cliente compre o imóvel por conta própria." },
            explanation: { es: "La hoja de visita es un documento importante para proteger la comisión del agente. La IA puede generar un documento listo para firmar, extrayendo los datos del CRM (nombre del cliente, dirección de la propiedad) y asegurando que el texto legal sea el correcto y esté actualizado según la jurisprudencia, protegiendo así el trabajo del agente.", pt: "A ficha de visita é um documento importante para proteger a comissão do agente. A IA pode gerar um documento pronto a assinar, extraindo os dados do CRM (nome do cliente, morada do imóvel) e garantindo que o texto legal está correto e atualizado de acordo com a jurisprudência, protegendo assim o trabalho do agente." }
        },
        {
            question: { es: "¿Qué es la 'Clasificación Automática de Documentos'?", pt: "O que é a 'Classificação Automática de Documentos'?" },
            answer: { es: "Es la capacidad de la IA para identificar qué tipo de documento es (una factura, un contrato, un DNI) sin que un humano tenga que etiquetarlo, y archivarlo en la carpeta correcta.", pt: "É a capacidade da IA para identificar que tipo de documento é (uma fatura, um contrato, um BI) sem que um humano tenha de o etiquetar, e arquivá-lo na pasta correta." },
            explanation: { es: "Un agente recibe decenas de documentos por email. Con la IA, puede reenviarlos todos a un sistema que automáticamente \"lee\" cada archivo, lo identifica (\"esto es un certificado energético para la propiedad X\") y lo mueve a la carpeta digital correspondiente. Esto ahorra horas de organización manual y asegura que todo esté siempre en su sitio.", pt: "Um agente recebe dezenas de documentos por e-mail. Com a IA, pode reencaminhá-los todos para um sistema que automaticamente \"lê\" cada ficheiro, o identifica (\"isto é um certificado energético para o imóvel X\") e o move para a pasta digital correspondente. Isto poupa horas de organização manual e garante que tudo está sempre no seu lugar." }
        },
        {
            question: { es: "¿Cómo se usa la IA para rastrear fechas de vencimiento en contratos?", pt: "Como se usa a IA para rastrear datas de vencimento em contratos?" },
            answer: { es: "La IA extrae las fechas clave de los contratos (fin de un alquiler, fin de un mandato de exclusiva) y crea recordatorios automáticos en el calendario del agente.", pt: "A IA extrai as datas-chave dos contratos (fim de um arrendamento, fim de um mandato de exclusividade) e cria lembretes automáticos no calendário do agente." },
            explanation: { es: "Olvidar la fecha de fin de un contrato de exclusiva puede significar perder la propiedad. La IA escanea el contrato, identifica la fecha de fin y puede programar una alerta para el agente: \"Recordatorio: Tu exclusiva sobre la propiedad X vence en 30 días. Es momento de hablar con el propietario para la renovación\". Esto convierte la gestión de la cartera en un proceso proactivo.", pt: "Esquecer a data de fim de um contrato de exclusividade pode significar perder o imóvel. A IA digitaliza o contrato, identifica a data de fim e pode agendar um alerta para o agente: \"Lembrete: A sua exclusividade sobre o imóvel X expira em 30 dias. É hora de falar com o proprietário para a renovação\". Isto transforma a gestão da carteira num processo proativo." }
        },
        {
            question: { es: "¿Qué es un 'Data Room' virtual inteligente?", pt: "O que é um 'Data Room' virtual inteligente?" },
            answer: { es: "Es un espacio online seguro donde se almacenan todos los documentos de una propiedad. Es 'inteligente' cuando usa IA para organizar los documentos, hacerlos buscables por contenido y analizar riesgos.", pt: "É um espaço online seguro onde se armazenam todos os documentos de um imóvel. É 'inteligente' quando usa IA para organizar os documentos, torná-los pesquisáveis por conteúdo e analisar riscos." },
            explanation: { es: "Para la venta de un activo complejo, se crea un 'Data Room' al que los posibles compradores acceden para la 'due diligence'. Un Data Room con IA permite a los inversores hacer preguntas en lenguaje natural como \"¿Hay algún litigio pendiente sobre esta propiedad?\" y la IA buscará la respuesta en los cientos de documentos almacenados, agilizando enormemente el proceso de análisis.", pt: "Para a venda de um ativo complexo, cria-se um 'Data Room' ao qual os potenciais compradores acedem para a 'due diligence'. Um Data Room com IA permite que os investidores façam perguntas em linguagem natural como \"Existe algum litígio pendente sobre este imóvel?\" e a IA procurará a resposta nas centenas de documentos armazenados, agilizando enormemente o processo de análise." }
        },
        {
            question: { es: "¿Puede la IA analizar los estatutos de una comunidad de propietarios?", pt: "Pode a IA analisar os estatutos de um condomínio?" },
            answer: { es: "Sí, puede leer los estatutos y extraer información clave como si se permiten alquileres turísticos, las normas sobre obras o si hay derramas importantes aprobadas.", pt: "Sim, pode ler os estatutos e extrair informação-chave como se são permitidos arrendamentos turísticos, as regras sobre obras ou se existem derramas importantes aprovadas." },
            explanation: { es: "Los estatutos pueden ser largos y complejos. La IA puede generar un resumen de los puntos más relevantes para un comprador: \"Puntos clave de los estatutos: 1. Prohibido el alquiler turístico. 2. Obras en fachada aprobadas con un coste de 2.000€ por propietario a pagar el próximo año. 3. No se admiten mascotas en las zonas comunes\". Esta información es crucial para la decisión de compra.", pt: "Os estatutos podem ser longos e complexos. A IA pode gerar um resumo dos pontos mais relevantes para um comprador: \"Pontos-chave dos estatutos: 1. Proibido o arrendamento turístico. 2. Obras na fachada aprovadas com um custo de 2.000€ por condómino a pagar no próximo ano. 3. Não são permitidos animais de estimação nas áreas comuns\". Esta informação é crucial para a decisão de compra." }
        },
        {
            question: { es: "¿Qué es una 'auditoría de cumplimiento normativo' con IA?", pt: "O que é uma 'auditoria de conformidade normativa' com IA?" },
            answer: { es: "Es el uso de IA para revisar todos los documentos y procesos de una agencia y verificar que cumplen con la legislación vigente (protección de datos, ley de vivienda, etc.).", pt: "É o uso de IA para rever todos os documentos e processos de uma agência e verificar se cumprem a legislação em vigor (proteção de dados, lei da habitação, etc.)." },
            explanation: { es: "La IA puede escanear la base de datos de clientes para asegurarse de que todos tienen un consentimiento de datos firmado (cumplimiento GDPR). Puede revisar los contratos de alquiler para verificar que incluyen las cláusulas obligatorias por la nueva ley de vivienda. Esta auditoría automática ayuda a la agencia a evitar multas y sanciones.", pt: "A IA pode digitalizar a base de dados de clientes para garantir que todos têm um consentimento de dados assinado (conformidade RGPD). Pode rever os contratos de arrendamento para verificar se incluem as cláusulas obrigatórias pela nova lei da habitação. Esta auditoria automática ajuda a agência a evitar multas e sanções." }
        },
        {
            question: { es: "¿Cómo ayuda la IA en la gestión de un 'parte de incidencias' de un alquiler?", pt: "Como a IA ajuda na gestão de um 'relatório de incidentes' de um arrendamento?" },
            answer: { es: "Un inquilino puede reportar una incidencia (ej. 'la caldera no funciona') a un chatbot. La IA puede crear un 'ticket', notificar al propietario y al técnico de mantenimiento adecuado, y registrar todo el proceso.", pt: "Um inquilino pode reportar um incidente (ex. 'a caldeira não funciona') a um chatbot. A IA pode criar um 'ticket', notificar o proprietário e o técnico de manutenção adequado, e registar todo o processo." },
            explanation: { es: "La gestión de alquileres implica muchas pequeñas incidencias. La IA puede actuar como el primer nivel de atención. Entiende el problema, lo clasifica por urgencia, y activa el protocolo correspondiente, todo de forma automática. Esto mejora el servicio al inquilino y libera al gestor de la propiedad de tareas repetitivas.", pt: "A gestão de arrendamentos envolve muitos pequenos incidentes. A IA pode atuar como o primeiro nível de atendimento. Entende o problema, classifica-o por urgência, e ativa o protocolo correspondente, tudo de forma automática. Isto melhora o serviço ao inquilino e liberta o gestor do imóvel de tarefas repetitivas." }
        },
        {
            question: { es: "¿Qué es la 'anonimización de documentos' con IA?", pt: "O que é a 'anonimização de documentos' com IA?" },
            answer: { es: "Es un paso más allá de la redacción. La IA no solo tacha los datos personales, sino que los reemplaza con datos ficticios pero coherentes (ej. 'Juan Pérez' por 'Cliente A'), para poder usar el documento como ejemplo sin violar la privacidad.", pt: "É um passo além da redação. A IA não apenas tacha os dados pessoais, mas substitui-os por dados fictícios mas coerentes (ex. 'João Silva' por 'Cliente A'), para poder usar o documento como exemplo sem violar a privacidade." },
            explanation: { es: "Si un agente quiere mostrar un contrato de arras como ejemplo a un nuevo cliente, no puede mostrar los datos reales. La anonimización con IA permite crear una versión 'limpia' del documento que mantiene la estructura y el formato, pero protege la confidencialidad de las partes originales.", pt: "Se um agente quer mostrar um contrato-promessa como exemplo a um novo cliente, não pode mostrar os dados reais. A anonimização com IA permite criar uma versão 'limpa' do documento que mantém a estrutura e o formato, mas protege a confidencialidade das partes originais." }
        },
        {
            question: { es: "¿Puede la IA ayudar a rellenar formularios de la administración pública?", pt: "Pode a IA ajudar a preencher formulários da administração pública?" },
            answer: { es: "Sí, extrayendo los datos necesarios de los documentos de la propiedad y del cliente (del CRM) y rellenando automáticamente los campos de los formularios digitales, como los del pago de impuestos.", pt: "Sim, extraindo os dados necessários dos documentos do imóvel e do cliente (do CRM) e preenchendo automaticamente os campos dos formulários digitais, como os do pagamento de impostos." },
            explanation: { es: "Rellenar formularios es una tarea tediosa y propensa a errores. La IA puede actuar como un asistente que ya conoce todos los datos (referencia catastral, DNI del comprador, precio de venta) y puede autocompletar la mayoría de los campos de un formulario de impuestos como el ITP (Impuesto de Transmisiones Patrimoniales), dejando al agente solo la tarea de revisar y firmar.", pt: "Preencher formulários é uma tarefa aborrecida e propensa a erros. A IA pode atuar como um assistente que já conhece todos os dados (referência cadastral, NIF do comprador, preço de venda) e pode preencher automaticamente a maioria dos campos de um formulário de impostos como o IMT (Imposto Municipal sobre as Transmissões Onerosas de Imóveis), deixando ao agente apenas a tarefa de rever e assinar." }
        },
        {
            question: { es: "¿Qué es la 'validación cruzada de datos' con IA?", pt: "O que é a 'validação cruzada de dados' com IA?" },
            answer: { es: "Es el proceso de la IA de verificar que los datos son consistentes a través de diferentes sistemas. Por ejemplo, que el precio en el contrato de arras coincide con el precio registrado en el CRM.", pt: "É o processo da IA de verificar se os dados são consistentes entre diferentes sistemas. Por exemplo, se o preço no contrato-promessa coincide com o preço registado no CRM." },
            explanation: { es: "Un pequeño error de transcripción puede causar grandes problemas. La IA puede actuar como un supervisor. Si detecta una discrepancia (ej. el precio en el CRM es 250.000€ pero el contrato generado dice 25.000€), puede lanzar una alerta al agente: \"Revisar precio: el valor en el contrato parece incorrecto\". Esto añade una capa de seguridad contra errores humanos.", pt: "Um pequeno erro de transcrição pode causar grandes problemas. A IA pode atuar como um supervisor. Se detetar uma discrepância (ex. o preço no CRM é 250.000€ mas o contrato gerado diz 25.000€), pode lançar um alerta ao agente: \"Rever preço: o valor no contrato parece incorreto\". Isto adiciona uma camada de segurança contra erros humanos." }
        },
        {
            question: { es: "¿Cómo se aplica el 'análisis de imágenes' a los documentos?", pt: "Como se aplica a 'análise de imagens' aos documentos?" },
            answer: { es: "La IA puede 'leer' planos arquitectónicos para extraer el número de habitaciones y metros cuadrados, o analizar un certificado para verificar si tiene un sello o firma oficial.", pt: "A IA pode 'ler' plantas de arquitetura para extrair o número de divisões e a área, ou analisar um certificado para verificar se tem um selo ou assinatura oficial." },
            explanation: { es: "La tecnología de 'visión por computador' no solo sirve para fotos de propiedades. Puede interpretar documentos visuales. Es especialmente útil para analizar planos, donde puede identificar y medir espacios automáticamente, o para verificar la autenticidad de un documento buscando elementos visuales específicos como sellos notariales o firmas manuscritas.", pt: "A tecnologia de 'visão computacional' não serve apenas para fotos de imóveis. Pode interpretar documentos visuais. É especialmente útil para analisar plantas, onde pode identificar e medir espaços automaticamente, ou para verificar a autenticidade de um documento procurando elementos visuais específicos como selos notariais ou assinaturas manuscritas." }
        },
        {
            question: { es: "¿Qué es una 'cadena de custodia digital' para un documento?", pt: "O que é uma 'cadeia de custódia digital' para um documento?" },
            answer: { es: "Es un registro inmutable (a menudo basado en blockchain) que traza todo el ciclo de vida de un documento: quién lo creó, quién lo vio, quién lo modificó y quién lo firmó, garantizando su integridad.", pt: "É um registo imutável (frequentemente baseado em blockchain) que rastreia todo o ciclo de vida de um documento: quem o criou, quem o viu, quem o modificou e quem o assinou, garantindo a sua integridade." },
            explanation: { es: "En transacciones de alto valor, asegurar que un documento no ha sido alterado es crucial. Una cadena de custodia digital proporciona una prueba auditable de todo lo que le ha ocurrido al documento. Si hay una disputa, se puede demostrar criptográficamente que la versión firmada es la original y no ha sido modificada.", pt: "Em transações de alto valor, garantir que um documento não foi alterado é crucial. Uma cadeia de custódia digital fornece uma prova auditável de tudo o que aconteceu ao documento. Se houver uma disputa, pode-se demonstrar criptograficamente que a versão assinada é a original e não foi modificada." }
        },
        {
            question: { es: "¿Puede la IA ayudar a redactar una 'oferta de compra' formal?", pt: "Pode a IA ajudar a redigir uma 'proposta de compra' formal?" },
            answer: { es: "Sí, un agente puede introducir los términos de la oferta en una app, y la IA genera un documento formal y profesional listo para ser enviado al vendedor o a su agente.", pt: "Sim, um agente pode introduzir os termos da oferta numa aplicação, e a IA gera um documento formal e profissional pronto a ser enviado ao vendedor ou ao seu agente." },
            explanation: { es: "Una oferta verbal puede dar lugar a malentendidos. Presentar una oferta por escrito es más profesional. La IA puede generar este documento incluyendo todos los elementos necesarios: identificación del comprador y la propiedad, precio ofrecido, validez de la oferta, y cualquier condición especial (ej. 'sujeto a inspección técnica').", pt: "Uma oferta verbal pode levar a mal-entendidos. Apresentar uma oferta por escrito é mais profissional. A IA pode gerar este documento incluindo todos os elementos necessários: identificação do comprador e do imóvel, preço oferecido, validade da proposta, e qualquer condição especial (ex. 'sujeito a inspeção técnica')." }
        },
        {
            question: { es: "¿Cómo se utiliza la IA para analizar el 'Registro de la Propiedad'?", pt: "Como se utiliza a IA para analisar o 'Registo Predial'?" },
            answer: { es: "Automatizando la consulta y el análisis de las notas simples de todas las propiedades en una zona para detectar patrones, como qué bancos están dando más hipotecas o si un gran inversor está comprando en el área.", pt: "Automatizando a consulta e a análise das certidões de registo predial de todos os imóveis numa zona para detetar padrões, como que bancos estão a conceder mais créditos à habitação ou se um grande investidor está a comprar na área." },
            explanation: { es: "El Registro de la Propiedad es una fuente de datos masiva. Un humano no puede analizarla a gran escala. La IA sí. Puede, por ejemplo, detectar que un fondo de inversión ha comprado 20 propiedades en un mismo edificio en los últimos 3 meses, una señal de mercado muy valiosa para un agente que trabaja en esa zona.", pt: "O Registo Predial é uma fonte de dados massiva. Um humano не pode analisá-la em grande escala. A IA pode. Pode, por exemplo, detetar que um fundo de investimento comprou 20 imóveis no mesmo prédio nos últimos 3 meses, um sinal de mercado muito valioso para um agente que trabalha nessa zona." }
        },
        {
            question: { es: "¿Qué es un 'repositorio de cláusulas' inteligente?", pt: "O que é um 'repositório de cláusulas' inteligente?" },
            answer: { es: "Es una base de datos de cláusulas contractuales que la IA puede usar para construir contratos. Es 'inteligente' porque la IA puede sugerir la cláusula más adecuada para cada situación.", pt: "É uma base de dados de cláusulas contratuais que a IA pode usar para construir contratos. É 'inteligente' porque a IA pode sugerir a cláusula mais adequada para cada situação." },
            explanation: { es: "En lugar de tener plantillas de contratos enteros, se tiene una biblioteca de 'bloques de construcción' (cláusulas). Cuando se redacta un contrato, la IA selecciona las cláusulas necesarias. Si el agente indica que es un 'alquiler de temporada', la IA sabe que debe incluir la 'cláusula de duración específica' y no la de 'prórroga forzosa' de un alquiler de larga duración.", pt: "Em vez de ter modelos de contratos inteiros, tem-se uma biblioteca de 'blocos de construção' (cláusulas). Quando se redige um contrato, a IA seleciona as cláusulas necessárias. Se o agente indicar que é um 'arrendamento de temporada', a IA sabe que deve incluir a 'cláusula de duração específica' e não a de 'renovação obrigatória' de um arrendamento de longa duração." }
        },
        {
            question: { es: "¿Cuál es el futuro de la gestión documental con IA en el sector inmobiliario?", pt: "Qual é o futuro da gestão documental com IA no setor imobiliário?" },
            answer: { es: "Transacciones casi instantáneas basadas en 'smart contracts' y blockchain, donde la verificación, firma y transferencia de la propiedad ocurran de forma totalmente digital, segura y automática.", pt: "Transações quase instantâneas baseadas em 'smart contracts' e blockchain, onde a verificação, assinatura e transferência da propriedade ocorram de forma totalmente digital, segura e automática." },
            explanation: { es: "El futuro apunta a eliminar el papeleo por completo. La propiedad será un 'token' digital en una blockchain. Comprar una casa podría ser tan rápido y seguro como comprar una acción. Toda la 'due diligence' la haría la IA en segundos, el 'smart contract' se ejecutaría automáticamente al transferir los fondos, y el registro de la propiedad se actualizaría al instante. Aunque aún falta para esto, es la dirección hacia la que se mueve la tecnología PropTech.", pt: "O futuro aponta para a eliminação total da papelada. A propriedade será um 'token' digital numa blockchain. Comprar uma casa poderá ser tão rápido e seguro como comprar uma ação. Toda a 'due diligence' seria feita pela IA em segundos, o 'smart contract' executar-se-ia automaticamente ao transferir os fundos, e o registo predial seria atualizado instantaneamente. Embora ainda falte para isto, é a direção para a qual a tecnologia PropTech está a avançar." }
        }
    ]
};